### ISSUE TITLE
Convert CSV line to avro format

### ISSUE THREAD

**Issue by kishaningithub** [hamba/avro#103]
# Background

We have a very specific use case where the data is in a CSV file and there is a separate file which stores avro schema.
We will have to convert the csv data into OCF format and send it out.

The problem we face is the CSV data is array of strings, and because of this  we get errors like
```
error: avro: string is unsupported for Avro long
```

For example

Schema

```avsc
{
  "type": "record",
  "name": "simple",
  "namespace": "org.hamba.avro",
  "fields": [
    { "name": "a", "type": "long" },
    { "name": "b", "type": "string"}
  ]
}
```

Value

```go
map[string]interface{}{
  "a": "27",
  "b": "foo",
}
```

We get an error like
```
error: avro: string is unsupported for Avro long
```

Play ground link - https://play.golang.org/p/P1Vz76K3F_E

# Feature request

1. Can we auto parse string to a type required by the avro schema at run time?
2. Also if a data is not present(empty string) default value must be populated

**Comment by nrwiersma** [comment]
Hi,

Thanks for your interest in the project.

1. No, should you need this, you will need to do it yourself before trying to encode the value.
2. This is already possible using avro records, but again, the type must be correct.

In general no type fudging will be performed by the library as it is not its responsibility.

**Comment by kishaningithub** [comment]
@nrwiersma Thanks for the quick response. In that case can this library parse the schema and give out a field representation so that another library can write the dynamic type conversions

For example

https://github.com/allegro/json-avro-converter/blob/a50090bc25a1c234f9be07d089640a43b3c0e56c/converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonGenericRecordReader.java#L94

This implements dynamic type conversion to translate json to avro

The base for this is that `org.apache.avro:avro` library provided a Schema.Field abstraction

**Comment by nrwiersma** [comment]
Hi,

This is already possible with the schema as it stands. The Primitive Schema type can be interrogated for its type.

**Comment by kishaningithub** [comment]
@nrwiersma Was reading this one

https://pkg.go.dev/github.com/hamba/avro?utm_source=godoc#Schema

And was not able see how we can fetch schema of the fields using that. If possible, Can you point me to an example?

**Comment by kishaningithub** [comment]
Also i feel the most powerful part of the `Schema.Field` abstraction `org.apache.avro:avro` is the simplicity in writing code for union types type
1. https://github.com/allegro/json-avro-converter/blob/a50090bc25a1c234f9be07d089640a43b3c0e56c/converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonGenericRecordReader.java#L97
2. https://github.com/allegro/json-avro-converter/blob/a50090bc25a1c234f9be07d089640a43b3c0e56c/converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonGenericRecordReader.java#L148

I feel this can also be brought into this library. What are your thoughts on this @nrwiersma ?

**Comment by nrwiersma** [comment]
If the `Schema.Type()` is `Record` you cast to a `*RecordSchema` [ref] (https://pkg.go.dev/github.com/hamba/avro#RecordSchema). From there you can get the `Fields()` which returns a slice of [fields](https://pkg.go.dev/github.com/hamba/avro#Field). Use the `Type()` to get the type.

In general the Java way of doing things is not idiomatic in Go leading to some ugly code to work with it. I personally dont like having something as specific as `Fields` on an interface that is as general as `Schema` as only 1 type actually has it. In this case the cast to a record schema is far better in my opinion. As for unions, they are a whole other ball game. 

The code you linked is all very possible with the library as it stands, but using Go constructs.

**Comment by kishaningithub** [comment]
That clarifies a lot! Thanks for the detailed explanation @nrwiersma ! 

If possible can you share/point me to an example with unions.

**Comment by nrwiersma** [comment]
It follows the same pattern with *UnionSchema and Types().

**Comment by kishaningithub** [comment]
Curious question, Do you think

https://github.com/hamba/avro/blob/master/codec_dynamic.go

be leveraged to perform this conversion?

**Comment by nrwiersma** [comment]
No, it will not do the conversion. All Avro type mappings are stated in the ReadMe.
