### ISSUE TITLE
aliyun dts schema parsed with error "avro: union type must be unique"

### ISSUE THREAD

**Issue by rfancn** [hamba/avro#107]
Below is the schema which cannot be parsed correctly: https://github.com/LioRoger/subscribe_example/blob/master/avro/Record.avsc?spm=a2c4g.11186623.2.9.605f741acYavoL&file=Record.avsc

It reports the error: "avro: union type must be unique",  the problem comes from section:
```
{
        "name": "beforeImages",
        "default": null,
        "type": [
          "null",
          "string",
          {
            "type": "array",
            "items": [
              "null",
              "com.alibaba.dts.formats.avro.Integer",
              "com.alibaba.dts.formats.avro.Character",
              "com.alibaba.dts.formats.avro.Decimal",
              "com.alibaba.dts.formats.avro.Float",
              "com.alibaba.dts.formats.avro.Timestamp",
              "com.alibaba.dts.formats.avro.DateTime",
              "com.alibaba.dts.formats.avro.TimestampWithTimeZone",
              "com.alibaba.dts.formats.avro.BinaryGeometry",
              "com.alibaba.dts.formats.avro.TextGeometry",
              "com.alibaba.dts.formats.avro.BinaryObject",
              "com.alibaba.dts.formats.avro.TextObject",
              "com.alibaba.dts.formats.avro.EmptyObject"
            ]
          }
        ]
}
```

I am not familiar with avro specification,  so I cannot figure out what's the root cause, but "github.com/linkedin/goavro/v2" works well with this schema, is there any specification not implemented yet?

**Comment by nrwiersma** [comment]
Hi,

This is indeed a bug. The union check is not dereferencing the schema reference.

Thanks for reporting.

**Comment by rfancn** [comment]
thanks for your quick response.
