### ISSUE TITLE
unmarshal reports error: "avro: decode union type: unknown union type"

### ISSUE THREAD

**Issue by rfancn** [hamba/avro#109]
Try unmarshal data with below schema:

https://github.com/LioRoger/subscribe_example/blob/master/avro/Record.avsc?spm=a2c4g.11186623.2.9.605f741acYavoL&file=Record.avsc

The data we captured is：[dts.log](https://github.com/hamba/avro/files/6813805/dts.log)

```
schema,  _ := avro.Parse(ALIYUN_DTS_SCHEMA)

data, _ := ioutil.ReadFile("dts.log")

var record interface{}
err = avro.Unmarshal(schema, data, &record)
```

it reports error "avro: decode union type: unknown union type"， any hints?

**Comment by nrwiersma** [comment]
Hi,

You need to [register](https://pkg.go.dev/github.com/hamba/avro#Register) your schema names to Go types to use `interface{}`, as explained [here](https://github.com/hamba/avro#unions), so `avro` knows how to create the correct object. The other options is to unmarshal into a `map[string]interface{}`.

**Comment by rfancn** [comment]
still the same result if I using `map[string]interface{}`

**Comment by nrwiersma** [comment]
The issue is with your data. Your schema says the first item is a union which means the first thing should be an avro long but the value read is `169443916` which is not a valid schema index. 

In conclusion either your schema is wrong or your data is wrong.

**Comment by rfancn** [comment]
Thanks, I tried to conclude the schema from data, it seems it is really has some difference between the document points to. I used another one, then it works, thanks a lot.
