### ISSUE TITLE
Consider extensions point to hook into ser/de

### ISSUE THREAD

**Issue by dstendardi** [hamba/avro#110]
## Description of the problem

It could be practical to let library users hook into the serialization process. For example with GDPR regulation, field encryption can be an interesting add on : 
```
{"type": "string", "tags": ["pii"]}
```
With such schema as above, one could implement a function that encrypts the string before its serialized by Avro.

Do you think this could be a good addition or is there already an existing way to achieve it ?

**Comment by nrwiersma** [comment]
Hi,

If the the schema type is `string` and the type implements `encoding.TextMarshaler` the library will call the `MarshalText` function.

This could be extended to `BinaryMarshaler`. I would need to think harder about an `AvroMarshaler` type. I am not sure what issues would be encountered with this.

**Comment by dstendardi** [comment]
👍 thanks! I missed this part of the readme indeed. One limitation I see with the TextMarshaler approach is that schema is not the source of trust. For example let say you tag your field, with the PII, if the implementer omits to wrap the string into a type implementing `encoding.TextMarshaler`, then it would not be encrypted. Additionally, schema properties could contain parameters for the serialization (ie you may not want to handle financial data like an email)

Would the AvroMarshaler help in such case?

**Comment by nrwiersma** [comment]
No, `AvroMarshaler` would be a more generic form of `TextMarshaler`. 

The kind of hooks, based on schema meta, would be very very complex. The entire library would also be "littered" with hooks, which is not great and make the code a fair but more complex, never mind that there is no real way to to get the hooks in given the interface (I am intentionally keeping the library interface as simple as possible). 

It should be noted that such meta would be remove in canonical forms of the schema, which is often what is saved in registries and the like, so there is no guarantee that the meta will exist.

**Comment by dstendardi** [comment]
Thanks for the answer closing the question then :)
