### ISSUE TITLE
`date` encode/decode incorrect for small/large dates

### ISSUE THREAD

**Issue by maros7** [hamba/avro#129]
Similar to https://github.com/hamba/avro/issues/128. Unix time cannot be represented in nanoseconds for small/large values.

https://github.com/hamba/avro/blob/bf2e271ad1ccc1704d4de48270a6996caa9b046f/codec_native.go#L392-L400

https://github.com/hamba/avro/blob/bf2e271ad1ccc1704d4de48270a6996caa9b046f/reader_generic.go#L24

**Comment by nrwiersma** [comment]
What is your test case for this?

**Comment by maros7** [comment]
I'd have to adjust my code. But the gist is encoding a record that has a `date` logical type. I use min/max values, e.g. max value like `map[string]interface{}{"a_date": testutil.TimeParseDate(t, "9999-12-31")}`. Write that to a file, decode that file and check if it is the same `time.Time`.

**Comment by nrwiersma** [comment]
Can you see if the linked PR fixes your issue?

**Comment by maros7** [comment]
👍  Yes, #130 fixes it.
