### ISSUE TITLE
Would you consider exposing `field.Doc()`

### ISSUE THREAD

**Issue by dstendardi** [hamba/avro#131]
## Description of the problem

We are considering using hamba avro to validate our schema conforms to a given specification (naming, required fields etc, documentation etc..). 

Unfortunately the type `Field` does not expose a method to access the `doc` attribute, since it's a reserved property.

## Question

Would you consider a contribution to add a `Doc()` function to the type `Field` ?

**Comment by nrwiersma** [comment]
The library in its current state does not hold on to docs for any schema element, but this is planned for v2 which you can find the progress of in the `vnext` branch, but I cannot give time guarantees on at the moment. Just FYI.

Assuming this is done in a non-breaking way, I would accept the contribution in v1.

**Comment by dstendardi** [comment]
Thanks for the quick answer. Will close this question then and see what i can do.
