### ISSUE TITLE
Support for Generic Data

### ISSUE THREAD

**Issue by melihaydogd** [hamba/avro#135]
Hi, I am trying to serialize json string.

```
schema := `{
  "fields": [
    {
      "name": "id",
      "type": "int"
    },
    {
      "default": null,
      "name": "name",
      "type": [
        "null",
        "string"
      ]
    }
  ],
  "name": "example",
  "namespace": "namespace",
  "type": "record"
}`

json_data := "{\"id\": 10, \"name\": \"test\"}"
var result map[string]interface{}
json.Unmarshal([]byte(json_data), &result)

a := avro.DefaultConfig
avroSchema, _ := avro.Parse(schema)
buf, err := a.Marshal(avroSchema, result)
if err != nil {
	fmt.Println(err.Error())
}
```

I am getting the following error `avro: float64 is unsupported for Avro int`. Go automatically determines the types when creating JSON objects and those types are not compatible. Is there any way to create json object that is compatible with Avro?

**Comment by nrwiersma** [comment]
The json decoder will make all numbers float64. Avro is expecting an int but getting the float64 from json.

**Comment by melihaydogd** [comment]
Yes, I know. In my mind, there are two methods that can solve this:
1. Make the type double in the avro schema which I do not want to.
2. Parse the value in the json object to int. In this method, if I have multiple fields, I should iterate over the json object and change every fields' type to the expected type.

My question is that is there any function in this package or another package that implements the second method?

**Comment by nrwiersma** [comment]
You could try `mapstructure` to change it into a struct, then encode it.

**Comment by melihaydogd** [comment]
So, at the end, I should parse the fields to their expected type. There is no "json to avro converter" library in go. Is that right?

**Comment by nrwiersma** [comment]
Not that I am aware of.

**Comment by melihaydogd** [comment]
OK. Thank you for the answers.

**Comment by brunsgaard** [comment]
@nrwiersma would you be interested in a PR with this functionality? We are thinking about picking it up at some point.

**Comment by nrwiersma** [comment]
Could you be more specific about what you are proposing?
