### ISSUE TITLE
Efficient assembly of ocf files from already encoded avro messages

### ISSUE THREAD

**Issue by brunsgaard** [hamba/avro#142]
I have a case where I build ocf files from encoded avro messages coming from a kafka stream. I would like to build the ocf files without decoding the encoded avro. So essentially I would like hamba/avro to create the ocf writer and control the header and data blocks management, but just append the encoded avro messages to the ocf encoder/writer.

I dont think this is possible with the current interface, what would be needed for this to work and how do you think this should be implemented. If you want this in your library I will try to create a PR.

Thanks for your consideration.

**Comment by brunsgaard** [comment]
https://github.com/brunsgaard/avro/commit/420948578da33cc2ce403d961952aa63cb7000f0

This commit seems to do what I want, but the implementation is a hack and I would like to do a PR with your guidance, if it is something you want to support in this lib?

**Comment by nrwiersma** [comment]
Hi,

Thanks for this. You can indeed create a PR for this. In this case I would make the Encoder implement the io.Writer interface (give it a Write method) rather then jumping the Encode method.

**Comment by brunsgaard** [comment]
@nrwiersma the PR is ready for review and comments

**Comment by nrwiersma** [comment]
Closed by #143
