### ISSUE TITLE
Questions regarding the "default" functionality

### ISSUE THREAD

**Issue by gustavobuohernandes** [hamba/avro#145]
Hi guys, hope you are doing well. We have been using this lib for internal benchmarking and developing, and so far
have been getting the best performance out of other avro libraries for Golang :).

We were testing the functionality of assigning default values to a field using Hamba and have faced some difficulties.
Consider the code snippet below:

```go
package main

import (
	"fmt"
	"github.com/hamba/avro"
)
const (
	schemaSimpleRecord = `{
    "type": "record",
    "name": "simple",
    "namespace": "org.hamba.event",
    "fields" : [
        {"name": "a", "type": "string", "default": "some value"}
    ]
}`
)

type SimpleRecord struct {
	A string `avro:"a"`
}

func main() {
	sourceEvent := &SimpleRecord{}
	schema, _ := avro.Parse(schemaSimpleRecord)

	// Sender will Marshal the event and send to reader
	val, _ := avro.Marshal(schema, sourceEvent)

	destinyEvent := &SimpleRecord{}
	// Reader will decode the event, and we analyse its result
	_ = avro.Unmarshal(schema, val, destinyEvent)

	fmt.Println(destinyEvent)
}
```
Surplisingly, it gives us the following output:

```bash
&{}
```
However, we had expected it would give us the following output: 

```bash
&{some value}
```

Could you guys help us?

**Comment by nrwiersma** [comment]
Hi.

The default is only applied if the struct is missing the field. This is because an empty string is a valid string value, and the encoder cannot ignore it and use the default.

**Comment by gustavobuohernandes** [comment]
Hi @nrwiersma, thanks for the amazingly fast reply.
I didn't think about passing a struct without the corresponding field defined, but thinking about both Go's Zero Values and backward compatibility for schemas, it makes a lot of sense. It

For anyone that may stumble upon this issue, here is a working example:

```go
package main

import (
	"fmt"

	"github.com/hamba/avro"
)

const (
	schemaSimpleRecord = `{
    "type": "record",
    "name": "simple",
    "namespace": "org.hamba.event",
    "fields" : [
        {"name": "a", "type": "string", "default": "some value"}
    ]
}`
)

type SimpleRecord struct {
}

type SimpleRecordUpdated struct {
	A string `avro:"a"`
}

func main() {
	sourceEvent := &SimpleRecord{}
	schema, _ := avro.Parse(schemaSimpleRecord)

	// Sender will Marshal the event and send to reader
	val, _ := avro.Marshal(schema, sourceEvent)

	destinyEvent := &SimpleRecordUpdated{}
	// Reader will decode the event, and we analyse its result
	_ = avro.Unmarshal(schema, val, destinyEvent)

	fmt.Println(destinyEvent)
}
```
This will print the desired output.
