### ISSUE TITLE
Support recursive avro types

### ISSUE THREAD

**Issue by yellow-sky** [hamba/avro#146]
https://github.com/hamba/avro/issues/138

**Comment by EliaBracciSumo** [comment]
Hi, is there any ETA for this? Starting from version 2.15.0, I'm having issues parsing recursive schema (Union type). It works until version 2.14.0 but from higher version, it enters an infinte loop between lines github.com/hamba/avro/v2@v2.15.0/schema_walk.go:17 and github.com/hamba/avro/v2@v2.15.0/schema_walk.go:9

**Comment by EliaBracciSumo** [comment]
@nrwiersma for ref, this is the "issued" [PR](https://github.com/hamba/avro/pull/291/files)

**Comment by nrwiersma** [comment]
#138 is talking about recursive Go types, not recursive schemas. Please open a new issue with a small reproduction of your issue.

**Comment by EliaBracciSumo** [comment]
> #138 is talking about recursive Go types, not recursive schemas. Please open a new issue with a small reproduction of your issue.

Done https://github.com/hamba/avro/issues/318

**Comment by nrwiersma** [comment]
Fixed by #413
