### ISSUE TITLE
Supporting props on PrimitiveSchema

### ISSUE THREAD

**Issue by acamperi** [hamba/avro#158]
Hello,

I'm currently using the schema portion of this library to parse Avro schemas generated by Kafka Connect components. Specifically, I need to parse the schema and then generically walk it and build a corresponding internal schema in a different format. The problem I'm running into is that some of the generated Avro schemas have props on primitive schemas but this library doesn't support that (as far as I can tell). An example schema looks something like this:
```json
{
  "name": "Foo",
  "namespace": "some_namespace",
  "type": "record",
  "connect.name": "something_else_Foo",
  "fields": [
    {
      "default": "1970-01-01T00:00:00Z",
      "name": "created_at",
      "type": {
        "connect.default": "1970-01-01T00:00:00Z",
        "connect.name": "io.debezium.time.ZonedTimestamp",
        "connect.version": 1,
        "type": "string"
      }
    }
  ]
}
```
As far as I can tell from the library code, props are only supported on `RecordSchema`, `Field`, `EnumSchema`, `ArraySchema`, `MapSchema`, and `FixedSchema`, whereas in this case that field's type gets parsed as a `PrimitiveSchema`. Is this something that is intentionally not supported, or has it just not come up as a need yet? If it's the latter I'm happy to take a crack at implementing it myself and submitting a pull request, but I first wanted to check if that sounded ok to you.

Thanks!

**Comment by nrwiersma** [comment]
Hi,

It is purely something I did not think of. I would be happy to accept a PR for this.

Thanks.

**Comment by acamperi** [comment]
That sounds great! I just opened a PR (#161) with this functionality, please let me know if there's anything I missed in terms of how you like to structure the library's code, test coverage, best practices, etc.
