### ISSUE TITLE
Calls to Parse() and to Register() for union types

### ISSUE THREAD

**Issue by mdpaquin** [hamba/avro#180]
Hello!
This is mainly a question at this point. I am trying to identify an issue I am having and am not sure if this is a bug or something I am doing wrong. Here is what is doing on:

1 - All avro.Register() calls for my union types are done during init. Each structure registers itself and its children when applicable.
2 - When marshalling payloads, I do not seem to be facing any issues.
3 - When unmarshalling, I sometimes run into "avro: decode union type: unknown union type". I enabled UnionResolutionError to fail rather than get stuck with an unresolved map[string]any. (Note the sometimes here, in most cases during my tests, this seems to be working fine).
4 - I have just validated that re-registering the affected structs seems to be fixing the issue.
5 - Note that my schemas are cached internally and fetched from a Schema Registry using srclient, not the registry client provided in this package. I doubt any of this matters though.

There therefore seems to be something I am doing wrong or am not understanding correctly. My thought process was that I could be registering the necessary types at init and then, regardless of the number of times I am parsing schemas, the type cache will remain valid. 

Is there either a time or storage size limit I need to be mindful of or need to configure? Other than BlockLength, that does not seem to apply, I am not sure what else I am supposed to do.

Thanks for your help

**Comment by nrwiersma** [comment]
> Is there either a time or storage size limit I need to be mindful of or need to configure?

No, there is neither, assuming you are always using the same Config.

Without seeing code there is not much I can do to help.

**Comment by mdpaquin** [comment]
Guess it must've been really late last night....I found the fix this morning...Turns out I had forgotten to register one of the union types but it wasn't the one that was encoded in the payload so I forgot to check.

Sorry for the silly question 😬
