### ISSUE TITLE
Encoding an array of strings fails

### ISSUE THREAD

**Issue by dlahyani** [hamba/avro#181]
This is the schema:
```json
{
  "doc": "Event with array of strings",
  "name": "my_event",
  "namespace": "events",
  "type": "record",
  "fields": [
	{
	  "default": null,
	  "doc": "A nullable list of requirements, null or empty array means no special requirements",
	  "name": "requirements",
	  "type": [
		"null",
		{
		  "items": "string", 
		  "type": "array"
		}
	  ]
	}
  ]
}
```

This is the struct:
```go
type MyEvent struct {
	Requirements []string `avro:"requirements"`
}
```

Maybe I am missing something but AFAIU this should work and properly encode `MyEvent` instance using the given schema, however this fails with an error saying: *Requirements: avro: unable to resolve type []string*

This is the code that tries to encode an object of type `MyEvent` using the schema above:
```go
// schema is loaded using avro.Parse on the schema above.
e := MyEvent{Requirements: []string{"foo", "bar"}}
buf, err = avro.Marshal(schema, e)
```

Here's a Go playground allowing to easily reproduce the error:
https://go.dev/play/p/pOcqvLA9tvw

**Comment by nrwiersma** [comment]
Your struct does not match the schema. Union types must be a `*T` or one of the other options detailed [in the docs](https://github.com/hamba/avro#unions).

**Comment by dlahyani** [comment]
@nrwiersma thanks for the quick response.
Indeed when I change the field type to `*[]string` it works.
However I must wonder why is this required? An array is essentially sort of a pointer, its empty value is `nil` thus requiring a pointer to an array is redundant.

Also from the doc it's not super clear what needs to be done to make it work for array without pointer. Should I manually register the type "array:string"?

**Comment by nrwiersma** [comment]
From a Go PoV a nil slice and empty slice both have a length of 0 and a zero length avro array is still a valid array.

> its empty value is nil thus requiring a pointer to an array is redundant.
It is redundant to have a null union array in an avro schema, and it takes as much space as a zero length array. In general this is an unexpected use case so for simplicity I ignore the optimisations on slices and maps.

> Also from the doc it's not super clear what needs to be done to make it work for array without pointer. Should I manually register the type "array:string"?
Just remove the union all together, it is not needed.

**Comment by dlahyani** [comment]
> From a Go PoV a nil slice and empty slice both have a length of 0 and a zero length avro array is still a valid array.
> 
> > its empty value is nil thus requiring a pointer to an array is redundant.
You right, but nil array and empty array are not equal.

 
> It is redundant to have a null union array in an avro schema, and it takes as much space as a zero length array. In general this is an unexpected use case so for simplicity I ignore the optimisations on slices and maps.
> 
> > Also from the doc it's not super clear what needs to be done to make it work for array without pointer. Should I manually register the type "array:string"?
> 
> Just remove the union all together, it is not needed.
Sadly I can't do that, the schema is given. It is defined by an external system and it uses a union for newly added fields to maintain backward compatibility (i.e. allow values encoded with an older version of the schema to be decoded with the new version of the schema, or something like that).
