### ISSUE TITLE
Merging hundreds of small avro files efficiently and converting them to OCF

### ISSUE THREAD

**Issue by yusufozturk** [hamba/avro#186]
First of all, thanks for this project. It helped us a lot reduce our costs and let us improve speed.

Please let me describe our challenge. I hope it makes sense.

We have a lot of small OCF files coming from hundreds of devices every second. We are merging them in our service before sending it to our Clickhouse database, so we can send large files instead of small files to improve efficiency on database inserts.

But in order to merge these OCF files, our service reads them, converts them to go structs, appends on structs and then write again as a new file. But this operation costs us a lot because it uses extra CPU and lots of memory. So.. to eliminate this expensive operation:

![AvroDesign](https://user-images.githubusercontent.com/928600/195722954-c8be926f-bfc2-4b33-a76d-3ce05e02889a.png)

1. Lets assume this is our OCF file and we have hundreds of them per second.
2. Our all files have same schema. So instead of holding header in all of them, we would like to trim them during OCF creation.
3. All files will be written without headers so they can be easly merged by file operations.
4. Just before sending them to Clickhouse, we would like to append OCF header and send it to Clickhouse so CH can parse it.

If we don't use OCF file, just by appending Avro blocks, we are able to merge the files. But when we try to add OCF header, due to block count, we are not able to decode entire file. Is there an efficient way to reconstruct OCF header with new block numbers?

Thanks.

**Comment by yusufozturk** [comment]
I assume there is no easy way to create OCF header without knowing how many blocks you have and their size. According to specs:

```
A file data block consists of:

A long indicating the count of objects in this block.
A long indicating the size in bytes of the serialized objects in the current block, after any codec is applied
The serialized objects. If a codec is specified, this is compressed by that codec.
The file's 16-byte sync marker.
Thus, each block's binary data can be efficiently extracted or skipped without deserializing the contents. The combination of block size, object counts, and sync markers enable detection of corrupt blocks and help ensure data integrity.
```

So in this case, in order to convert avro blocks to OCF, I need to process all Avro lines, calculate total number of blocks and their size, then create the OCF header based on this information, am I correct?

But since this library is very fast to read blocks, and it can work in stream way, maybe it's not that expensive for us.

At the same time, I opened a feature request to Clickhouse so they can allow Avro blocks with schema as well. If they add that feature, we can skip OCF creation and send the blocks directly.

**Comment by nrwiersma** [comment]
That is not technically true. As long as your blocks are not bigger than the given block size, you could just read the block content (you know the size) and append the correct sync marker. This lib will not do that for you, but you could use an `avro.Reader` like `ocf` does this. The header itself does not know how many blocks there are, so that is not an impediment, but if your sync markers are wrong, that would be an issue.

**Comment by yusufozturk** [comment]
@nrwiersma Thanks for help!

Okay, so far I did great :) I changed the design a bit, but it solves some other problems for me. I use your "Write" method for the Encoder and it works great!

Now one feature request maybe. Is it possible to add Read() method for Decoder as well? Currently there is only a method for Decode to go struct but I would like to get the []byte value of the block only.

If I have that, I can merge different avro files by just reading their blocks and writing them directly to other OCF file.

Thanks.

**Comment by nrwiersma** [comment]
No, `Read()` is not possible as there is no way of knowing how many bytes an avro encoded message is, you have to effectively decode it to figure it out.

**Comment by yusufozturk** [comment]
How about OCF? If I send the files in OCF format, can I decode the OCF blocks to Read Bytes and use it in Write() ?

**Comment by nrwiersma** [comment]
You can read the entire block and use `Write` on the entire block, but the `ocf` Decoder will not do this for you, as it is out of its scope. I would suggest to do that you copy the existing Decoder and modify it to your needs.

**Comment by yusufozturk** [comment]
Thank you so much. It worked like a charm!

May I still send you a PR for this? I don't want to continue from a different branch. I can follow your guidlines if you are willing to accept PR.

Thanks.

**Comment by nrwiersma** [comment]
You are obviously welcome to open a PR, but I make no guarantees that it will be merged. The focus of the lib is the general use case. There are too many edge cases to include solutions to them all in this lib. But if it fits cleanly into the general case I am open to merging it. 

Just to manage expectations here.

**Comment by yusufozturk** [comment]
Totally fine. I will open the PR, feel free to close it if you think it’s not good enough.

Thanks for help again.

**Comment by yusufozturk** [comment]
We are merging 4 million messages in 262 milliseconds btw. Thanks a lot! @nrwiersma
