### ISSUE TITLE
When union type resolution fails, is there a way to easily parse the result map?

### ISSUE THREAD

**Issue by mdpaquin** [hamba/avro#191]
This might be a bit of a weird one. Here is my current scenario:

I have a root schema that contains a union of possible event payloads in a "data" field of the form `Data any`. When trying to unmarshal payloads using the root schema, there are 2 possible outcomes.

- The entity decoding knows about and has registered all of the possible union types. In this case, resolution does its job and the resulting structure is properly populated.
- The entity decoding has not registered 1 or more of the union types. This might be because the entity encoding is using newer definitions than the one decoding but they are sharing the same schema. In this case, type resolution fails and the 'Data' field is unmarshalled as a `map[string]any`, as documented.

For that second case, the message being decoded might be using a union type the entity decoding knows about and has properly registered, in this case, I dont want to ignore it but I am stuck having to deal with that map and how to populate the resulting structure with its content. My initial thought was to leverage something like the **mapstructure** package to do this by making sure the necessary checks were done before passing the map to its decoder.

Unfortunately, the output of the avro decoder is not fully compatible with mapstructure in quite a few cases because the avro type name or schema name is always added to the map, adding additional interface{} layers mapstructure does not parse.

Do you have a strategy to deal with those maps and still map the result to the corresponding structure if the payload is something that can be understood. I would rather avoid having to code my own map walker to deal with the output...

The best solution to my problem would either be, if they are even possible:

1 - Dont fail type resolution when unmarshalling without all union types registered IF the type encoded in the message is properly registered. I dunno if this is possible or if there is a technical reason for this?

2 - Have a way to generate a map[string]any that includes the schema name for non nullable unions only. For nullable unions, the schema name is somewhat redundant is it not? The map can either be null or contain `any` or `[]any` of a specific type

**Comment by nrwiersma** [comment]
Do you have a simplified of the problem in code, so I can fully understand your issue?

**Comment by mdpaquin** [comment]
_Apology for the wall of text, trying to give you as much context as I can._

In my use case, both producer and consumer share the same schema since the schema ID (stored in registry) is encoded in the message (see avro single object encoding). However, it may happen that a consumer's struct representation of a schema is behind the producer's for whatever reason (consumer has not been updated yet with the latest definitions for example). In those cases, I would want the consumer to consume only messages that are relevant to it and that he can properly resolve, acking/ignoring  the rest.

Take the following example schema that is very close something I current use:

```
{
  "name" : "Root",
  "type" : "record",
  "namespace" : "com.xxx.entity.entityType.events",
  "fields" : [
    { "name" : "id", "type" : "string" },
    { "name" : "version", "type" : "string" },
    { "name" : "actor", "type" : "string" },
    { "name" : "type", "type" : "string" },
    {
      "name" : "data",
      "type" : [
        {
          "name": "Event1",
          "type": "record",
          "fields": [
            { "name": "status", "type": ["null", "string"], "default": null },
            { "name": "arrayOfStrings", "type": { "type": "array", "items": "string" } },
            {
              "name": "external",
              "type": {
                "type": "array",
                "items": [
                  "null",
                  {
                    "name": "ExternalType",
                    "type": "com.xxx.entity.entityType.ExternalType"
                  }
                ]
              }
            },
            { "name": "aString", "type": "string" },
            { "name": "anotherString", "type": "string" },
            { "name": "aThirdString", "type": "string" }
          ]
        },
        {
          "name": "Event2",
          "type": "record",
          "fields": []
        },
        {
          "name": "Event3",
          "type": "record",
          "fields": [
            { "name": "aString", "type": "string" }
          ]
        }
      ]
    },
    { "name" : "created", "type": "string" }
  ]
}
```

In scenario 1, the consumer knows and has called avro.Register() on Event1, Event2, Event3 and ExternalType. This scenario works perfectly, the type resolution works great and the consumer has access to event content in its struct.

In scenario 2, the consumer does not know what Event3 is and has not registered it, it also does not care about it. It then receives a message where the data is of type Event2 which it knows about and wants to handle. Because the consumer has not registered all possible union types of data, it unmarshals the data field in a map[string]any. Since Event2 is an event I want to handle, I have to somehow manage to map the map[string]any into my struct. I have the following code that does the type resolution for me and determines how to deal with this:

```
// RawData a raw decoded data structure
type RawData = map[string]any

// MarshalHookFunc func called when marshalling data of a given type
type MarshalHookFunc func() error

// UnmarshalHookFunc func called when unmarshalling data of a given type
type UnmarshalHookFunc func(event *Event) error

// RegisterableEvent event that can registered and mapped from a valid map[string]any definition
type RegisterableEvent interface {
	EventType() string
	Register() (MarshalHookFunc, UnmarshalHookFunc)
}

type registeredEventEntry struct {
	event             RegisterableEvent
	marshalHookFunc   MarshalHookFunc
	unmarshalHookFunc UnmarshalHookFunc
}
...
func (h *SchemaAwareEventHandler) resolveEventDataType(sourceEvent *Event) error {
	var eventDataEntry registeredEventEntry
	var found bool
	var err error

	if eventDataEntry, found = h.registeredEventCache[sourceEvent.Type]; !found {
		// This event type is not currently tracked
		return e.NewEntityNotFound(fmt.Sprintf("event of type '%s' is not relevant for this consumer", sourceEvent.Type))
	}

	unmarshalHookFunc := eventDataEntry.unmarshalHookFunc // Base func
	switch reflect.TypeOf(sourceEvent.Data).Kind() {
	case reflect.Map:
		// If we receive a map, type resolution failed because this consumer does not have all the necessary
		// union types defined. We need to validate the content first
		rawData, ok := sourceEvent.Data.(RawData)
		if !ok {
			return fmt.Errorf("could now infer raw data")
		}
		if len(rawData) != 1 {
			return fmt.Errorf("expected event data to be of length 1, got %d", len(rawData))
		}

		expected := sourceEvent.Type
		actual := maps.Keys(rawData)[0]
		if expected != actual {
			return fmt.Errorf("expected type '%s' but got '%s'", expected, actual)
		}

		if unmarshalHookFunc == nil {
			// We minimally have to map this, set up the default unmarshalHookFunc
			unmarshalHookFunc = getDefaultUnmarshalHookFunc(&eventDataEntry)
		}

	case reflect.Pointer:
		// If we receive a pointer, we assume the unmarshaller managed to automatically resolve the type
		splitEventType := strings.Split(eventDataEntry.event.EventType(), ".")
		expected := splitEventType[len(splitEventType)-1]
		actual := GetTypeNameOf(sourceEvent.Data)
		if expected != actual {
			return fmt.Errorf("expected type '%s' but got '%s'", expected, actual)
		}

	default:
		return fmt.Errorf("expected a map or a pointer from '%s'", reflect.TypeOf(sourceEvent.Data).String())
	}

	if unmarshalHookFunc != nil {
		if err = unmarshalHookFunc(sourceEvent); err != nil {
			return fmt.Errorf("unmarshal hook func returned error: %w", err)
		}
	}

	return nil
}
```

Once I know what I am dealing with and have made the necessary validations, my unmarshalHookFunc is called. If I receive a ptr to a type, I know type resolution has worked and I have nothing to do in most cases. If it has not, I need to handle the mapping manually. The issue is it is not trivial to map and existing packages are not able to fully map the format output by the hamba/avro package.

I have the following options before me:

1 - If hamba/avro could ONLY return a map[string]any when encountering a union type not registered in the message rather than returning map[string]any as soon as one of the types (regardless of if its used in the message or not) is not registered. I could discriminate against the map and say, if type resolution has failed, then I am not interested in this message.

2 - If we could have a configuration option to perhaps return a map[string]any compatible with something like mapstructure. What is not working here that nullable unions is including  the schema name in the resulting map[string]any. if instead, we either the map to nil or to the expected element, mapstructure could walk it properly.

3 - The least desirable option here is to implement a custom walker to "clean up" the map before passing it on the mapstructure.

**Comment by nrwiersma** [comment]
Ok, I understand the problem, My thoughts on your options:
1. This seems inconsistent and it may become difficult to reason about what type you will get in the interface. 
2. Nullable unions decode into a map like this on purpose, otherwise there would be no way to determine which union type was decoded in some cases. I dont see this as a good option.
3. This could be an option.

I can offer a secret option 4. which is to add a config that returns an error when a registered type does not exist, rather than switching to a map. It could be a sentinel error like `ErrUnresolvableType` that would be easy to catch.

**Comment by mdpaquin** [comment]
Hello @nrwiersma,

I decided to run a few tests with Option 1 and it seems to solve my use case quite nicely. Here is the patch file with the changes I made just for reference, I dont want to push this through any kind of PR process just yet:

```
diff --git a/codec_union.go b/codec_union.go
index 9cb4031..068401b 100644
--- a/codec_union.go
+++ b/codec_union.go
@@ -236,6 +236,12 @@ func decoderOfResolvedUnion(cfg *frozenConfig, schema Schema) ValDecoder {
 			continue
 		}

+		if cfg.config.PartialUnionTypeResolution {
+			decoders[i] = nil
+			types[i] = nil
+			continue
+		}
+
 		decoders = []ValDecoder{}
 		types = []reflect2.Type{}
 		break
@@ -269,7 +275,7 @@ func (d *unionResolvedDecoder) Decode(ptr unsafe.Pointer, r *Reader) {
 		return
 	}

-	if i >= len(d.decoders) {
+	if i >= len(d.decoders) || d.decoders[i] == nil {
 		if d.cfg.config.UnionResolutionError {
 			r.ReportError("decode union type", "unknown union type")
 			return
diff --git a/config.go b/config.go
index cad1cd7..932a5f4 100644
--- a/config.go
+++ b/config.go
@@ -24,6 +24,12 @@ type Config struct {
 	// UnionResolutionError determines if an error will be returned
 	// when a type cannot be resolved while decoding a union.
 	UnionResolutionError bool
+
+	// PartialUnionTypeResolution dictates if the union type resolution
+	// is possible even when not all union types are registered.
+	// When enabled, type will get resolved if it is registered even if
+	// other types of the union are not.
+	PartialUnionTypeResolution bool
 }
```

Figured I would do this through a new configuration option if this is something you would consider adding in the code base. I am still actively testing this and am not 100% sure there are no deeper ramifications to this change, perhaps there is a very good reason you decided not to support this case?

Let me know what you think

**Comment by nrwiersma** [comment]
> For Option 1, could you explain where the inconsistency is coming from? We should have the union type encoded in the message so we should be able to determine if we have the correct types registered for the type resolution? If we do, we resolve, if not, we return the map[string] any? I am trying to identify the reason why we absolutely need to register all the union types to be able to successfully unmarshal the content, is there a technical reason?

We basically have 2 types of decoding here, one `map[string]any` and the other is typed. It would be consistent to use one or the other but never both. We cannot look at it message by message, as the same decoder is used for every Schema and type combination, and for any Schema we must assume all message combinations are possible.

> Figured I would do this through a new configuration option if this is something you would consider adding in the code base.

As it is an option and as long as normal behaviour is preserved as the default situation (all of which you have done), it is something I would consider.

**Comment by mdpaquin** [comment]
I have opened a PR for your consideration:
https://github.com/hamba/avro/pull/193.

Change is non intrusive and backed by a configuration option that is disabled by default. All tests I have run thus far behave as expected from the change and it does correctly fix my issues. If this is not something you want added in the codebase, I also understand.
