### ISSUE TITLE
Using JSON tag key doesn't work if omitempty present

### ISSUE THREAD

**Issue by stampy88** [hamba/avro#192]
When setting the `TagKey` on a `Config` to `json`, the code cannot match the `RecordSchema's` field with the field on the `structField` when the `omitempty` option is present. Below is an example of a struct that has this problem:
```
type TestJSONTagRecord struct {
	A int64  `json:"a"`
	B string `json:"b,omitempty"`
}
```
And a failing test:
```
func TestEncoder_RecordStructJSONTags(t *testing.T) {
	schema, err := avro.Parse(`{
	"type": "record",
	"name": "test",
	"fields" : [
		{"name": "a", "type": "long"},
	    {"name": "b", "type": "string"}
	]
}`)
	require.NoError(t, err)

	obj := TestJSONTagRecord{A: 27, B: "foo"}
	buf := &bytes.Buffer{}
	api := avro.Config{TagKey: "json"}.Freeze()
	enc := api.NewEncoder(schema, buf)

	err = enc.Encode(obj)

	require.NoError(t, err)
	assert.Equal(t, []byte{0x36, 0x06, 0x66, 0x6f, 0x6f}, buf.Bytes())
}
```
I thought of a couple of different options to handle this. Let me know what you think, and I'd be happy to make a PR:

- do a `strings.Cut(tag, ",")` on `field.Tag().Lookup(tagKey)` use the `"before"` of the return
- handle well-known tags, e.g. json differently
- allow users to specify a "tag parser" function in addition to a `TagKey` as part of the config. This would allow a user to take control of turning the value returned by `field.Tag().Lookup(tagKey)` into a name.

**Comment by nrwiersma** [comment]
This is because the `avro` tag does not support `omitempty` or any modifiers. The intention behind `TagKey` is not to jump it onto another tag, but just to let you rename the tag if you wish. 

The issue I see with simply ignoring the modifiers now, is of the tag needs modifiers later, this workaround will break.

**Comment by nrwiersma** [comment]
I have no reasonable way of knowing what people do. While I understand the intent, doing this will make any changes to the avro tag breaking, and this is not something I am willing to do.
