### ISSUE TITLE
ocf encoder's Flush() does not write out *just* the header

### ISSUE THREAD

**Issue by mibanescu** [hamba/avro#196]
If I wanted to write an empty Avro file (zero blocks, header only), we currently can't. The result is a zero-byte file.

In my opinion, it's useful to create a non-zero length file with zero records, if one only wants to convey the structure (i.e. schema).

The problem is that the encoder's `Flush` function will check for `e.count == 0` and immediately exit, instead of also flushing the underlying `e.writer`. And because `writer` is not exposed, we can't flush it manually in a different way.

**Comment by nrwiersma** [comment]
This is not consistent with the spec:

> A file consists of:
>
> * A file header, followed by
> * one or more file data blocks.

If you want to transport schema it should be done as just as JSON.

**Comment by mibanescu** [comment]
I do see that in the spec now. I was going by the very first paragraph:

> Avro includes a simple object container file format. A file has a schema, and all objects stored in the file must be written according to that schema, using binary encoding.

(emphasis on "A file has a schema" - an empty file has no schema).

**Comment by mibanescu** [comment]
Just for comparison:

The Python implementation is similar to the Go implementation: the header is written lazily on the first block write, so an empty file will be created. https://github.com/apache/avro/blob/master/lang/py/avro/datafile.py#L230

The C implementation writes out the header when the file is created, and a subsequent `avro_file_writer_flush` will persist the header in the file. https://github.com/apache/avro/blob/master/lang/c/src/datafile.c#L172

The Java implementation explicitly flushes after the header is written in `create`: https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/file/DataFileWriter.java#L175 (it also lets one use a specific sync block, something which I want as well, but that's for another story :-)

The C++ implementation is like the C one.

The C# implementation specifically calls `EnsureHeader` in `Flush`: https://github.com/apache/avro/blob/master/lang/csharp/src/apache/main/File/DataFileWriter.cs#L334

The Ruby implementation is like the C one: the header is written at init time, and a flush will write it out even with no data: https://github.com/apache/avro/blob/master/lang/ruby/lib/avro/data_file.rb#L114

**Conclusion**

There is no clear consensus. The spec has been interpreted the way I do by most implementations (and it would hugely help my use case to produce a file with an empty header).

Feel free to use your judgement - merge or close. I can work around this, but it's not the prettiest.

If you still entertain the idea, maybe adding an extra flavor of `Flush`() (like `FlushUnconditionally`) I can change the PR.
