### ISSUE TITLE
Enum support for TextMarshaler and TextUnmarshaler

### ISSUE THREAD

**Issue by stampy88** [hamba/avro#205]
Hi, I was wondering what your thoughts were about enum types supporting the  `TextMarshaler` and `TextUnmarshaler` much like this https://github.com/hamba/avro/pull/68. A lot of our "enums" in Go are integers, so converting the integer into the symbol would allow us to keep our enums as non-strings in the Go space.

Thanks!

**Comment by stampy88** [comment]
Thanks, I will give it a try and let you know

**Comment by stampy88** [comment]
Hi @nrwiersma, this seems to only work if you define the field on the struct as a pointer, not a value. This test fails, but if you change `C testEnumTextUnmarshaler` to `C *testEnumTextUnmarshaler`, it works.
```


func TestDecoder_RecordStructWithEnum(t *testing.T) {
	defer ConfigTeardown()

	data := []byte{0x36, 0x06, 0x66, 0x6f, 0x6f, 0x02}
	schema := `{
	"type": "record",
	"name": "test",
	"fields" : [
		{"name": "a", "type": "long"},
	        {"name": "b", "type": "string"},
                {"name": "c", "type": {"name":"testEnumTextUnmarshaler", "type":"enum", "symbols": ["foo", "bar"]}}
	]
}`
	dec, err := avro.NewDecoder(schema, bytes.NewReader(data))
	require.NoError(t, err)

	type TestRecord struct {
		A int64                   `avro:"a"`
		B string                  `avro:"b"`
		C testEnumTextUnmarshaler `avro:"c"`
	}
	var got TestRecord
	err = dec.Decode(&got)

	require.NoError(t, err)
	one := testEnumTextUnmarshaler(1)
	assert.Equal(t, TestRecord{A: 27, B: "foo", C: one}, got)
}

**Comment by nrwiersma** [comment]
This is expected as the `TextUnmarshal` function must be on a pointer in order the change the `testEnumTextUnmarshaler`.

**Comment by nrwiersma** [comment]
The short answer is no. The trick they use to make that possible, I don't have access to.

**Comment by stampy88** [comment]
Interesting. What is the trick? You have piqued my curiosity :) Thanks

**Comment by nrwiersma** [comment]
They are using `reflect` so it is possible to call `CanAddr` and `Addr` to grab a pointer to the object. If the object is not a pointer, they check it is addressable and move to a pointer of the object, and this allows the type cast to succeed. `avro` does not use `reflect` as it ends up being very very slow, instead we use `reflect2` which does not give me the ability to grab the pointer of the type I have. While I could move the `Type` to a pointer type, it does not actually give me the pointer value.

**Comment by nrwiersma** [comment]
It turns out I lied. I think I have found a way for it to behave the way you want, it was just not obvious to me until I trawled the `reflect2` codebase again. Please try #208 and let me know if it works for you?

**Comment by dsincl002c** [comment]
This works perfectly, @nrwiersma. Glad there was a way to do it. Thanks again! Any idea when a release will be created that contains this?

**Comment by nrwiersma** [comment]
Awesome. Most likely cut a release late next week.
