### ISSUE TITLE
Encoding objects with big arrays

### ISSUE THREAD

**Issue by vckamanga** [hamba/avro#215]
Hi,

I'm encoding some data into Avro OCF (using snappy compression), and then loading it into google big query (BQ). One field on my data objects is an array, and when the array has a lot of elements, I get the following error when loading into BQ:

`2022/11/29 13:26:56 bq load error: job completed with error: {Location: "bigstore/vkamanga/test-2022-11-29T19:26:53.864771Z.avro"; Message: "Error while reading data, error message: The Apache Avro library failed to read data with the following error: Value out of range for Avro int: 1669750013865241 File: bigstore/vkamanga/test-2022-11-29T19:26:53.864771Z.avro"; Reason: "invalid"}`

I tried encoding the exact same data with a different library - https://www.perfectlyrandom.org/2019/11/29/handling-avro-files-in-python/ - and I was able to load the resulting avro file into BQ.

One notable difference between hamba/avro and the python lib was the size of the resulting avro file:
```
➜  Downloads/ du -hs vistas-*
 36K	vistas-1.avro (hamba/avro)
160K	vistas-2.avro (python avro)
```

Any ideas on what may be going on?

Code snippet:
```
var schema = `{
    "type": "record",
    "name": "test",
    "namespace": "test",
    "doc": "docstring",
	"fields": [
		{ "name": "name","type": "string" },
		{ "name": "values","type": { "type" : "array", "items": {"name": "values","type":"string"}}},
		{ "name": "test_time","type": {"logicalType": "timestamp-micros", "type": "long"}}
	]
}`

type MyRecord struct {
	Name     string    `json:"name,omitempty" avro:"name"`
	Values   []string  `json:"values,omitempty" avro:"values"`
	TestTime time.Time `json:"test_time,omitempty" avro:"test_time"`
}

func main() {
	ctx := context.Background()

	creds := os.Getenv("GCP_CREDS")
	projectName := os.Getenv("BQ_PROJECT")

	// clients
	gcpStorageClient, err := newGcsStorageClient(ctx, creds)
	if err != nil {
		log.Fatal(err)
	}
	bqClient, err := newBigQueryClient(ctx, creds, projectName)
	if err != nil {
		log.Fatal(err)
	}

	collection := "test"
	timeNow, _ := time.Now().UTC().MarshalText()
	fileName := fmt.Sprintf("%s-%s.avro", collection, timeNow)
	filePath := fmt.Sprintf("/tmp/%s", fileName)
	f, err := os.OpenFile(filePath, os.O_WRONLY|os.O_TRUNC|os.O_CREATE, 0666)
	if err != nil {
		log.Fatal(err)
	}
	defer func() { _ = f.Close() }()

	enc, err := ocf.NewEncoder(schema, f, ocf.WithCodec("snappy"))
	if err != nil {
		log.Fatal(err)
	}
	defer func() { _ = enc.Close() }()

	record := &MyRecord{
		Name:     "test-name",
		TestTime: time.Now(),
	}
	// Add big array
	for i := 0; i < 200; i++ {
		record.Values = append(record.Values, fmt.Sprintf("val-%d", i))
	}

	err = enc.Encode(record)
	if err != nil {
		log.Fatal(err)
	}
	if err = enc.Flush(); err != nil {
		log.Fatal(err)
	}
	if err = f.Sync(); err != nil {
		log.Fatal(err)
	}

	if err = storeGCSFile(ctx, filePath, bucketName, fileName, gcpStorageClient); err != nil {
		log.Fatal(err)
	}

	if err = bqImportAvro(ctx, bqClient, dataset, tableID, fmt.Sprintf("gs://%s/%s", bucketName, fileName)); err != nil {
		log.Fatalf("bq load error: %v", err)
	}
}
```

**Comment by nrwiersma** [comment]
Hi,

There is not enough information here for me to understand what is happening. Please provide a schema and code snippet that reproduces the error in an isolated form.

**Comment by vckamanga** [comment]
Appreciate the response @nrwiersma . I've update the description with a code snippet. Happy to share more if needed.

**Comment by nrwiersma** [comment]
I cannot reproduce an issue with the given code. I use it to write the avro file, and once again read it, and the result is correct. I have used a different reader to read the file, and that too is correct (https://dataformat.net/avro/viewer-and-converter). 

Either the issue is not in the avro library, or I would need code and a schema that produces a "broken" avro file.

**Comment by vckamanga** [comment]
That's right. I was also able to read it with other readers too. I suppose there's something with whatever reader BQ loader is using. Anyways, https://github.com/linkedin/goavro seems to be producing an avro file that's readable by BQ. Only annoying thing is that it doesn't allow me to omit empty fields.

Thanks for taking a look @nrwiersma

**Comment by vckamanga** [comment]
I did try without compression, and I ran into the same error. I'll dig some more into understanding the diff between this lib and linkedin's. Ciao!
