### ISSUE TITLE
Union implementing common interface

### ISSUE THREAD

**Issue by stampy88** [hamba/avro#219]
Hi,

I was trying to get the library to support decoding a union where the members of the union all implemented an interface, and the interface was what was specified on the enclosing struct (instead of a `interface{}`, `map`, etc.). Example (Record is the common interface):
```

type Record interface {
	DoIt()
}

type RecordHolder struct {
	A Record `avro:"a"`
}

type Record1 struct {
	B string `avro:"b"`
}

func (r Record1) DoIt() {

}

type Record2 struct {
	A int64  `avro:"a"`
	B string `avro:"b"`
}

func (r Record2) DoIt() {

}

```
I have updated `createDecoderOfUnion` to ensure that all members of the union implement the interface the field is declared as, but haven't been able to figure out the changes to ` (d *unionResolvedDecoder) Decode(ptr unsafe.Pointer, r *Reader)` to make this work (if it is even possible).  I'll keep at it, but I wanted to get your thoughts to see if this is possible.

Thanks

**Comment by nrwiersma** [comment]
In theory it is possible, but the existing code there is all dealing in efaces and not ifaces, so the code in the end might look different.

**Comment by stampy88** [comment]
OK, I'll try and look into this when I get some more free time. Will open a PR if I am able to come up with a good solution. 

Thanks
