### ISSUE TITLE
Support for other types of fingerprint algorithms and single-object encoding

### ISSUE THREAD

**Issue by przemekd** [hamba/avro#22]
Being able to define a fingerprint algorithm other than SHA256 would be nice and it's necessary if you want to support single-object encoding spec (https://avro.apache.org/docs/1.9.0/spec.html#single_object_encoding_spec). Do you plan to add those features? Will you accept PRs?

**Comment by nrwiersma** [comment]
I dont have plans to at the moment, as Single Object Encoding is generally not used for Kafka any more. More often than not the Confluent Encoding and Registry is used, and a registry client is provided in the [registry](https://github.com/hamba/avro/tree/master/registry) package. 

Is this what you need it for, Kafka? Or do you need it for something else?

**Comment by przemekd** [comment]
@nrwiersma I need it for my custom system that doesn't use Kafka.

**Comment by nrwiersma** [comment]
Fair enough. You have thoughts on how to integrate this. I need SHA256 to be the "default" fingerprint, as it is used else where. Perhaps the algorithm could be passed to the fingerprint function.

**Comment by przemekd** [comment]
This or the algorithm label could be passed to the fingerprint function e.g.:
`fp, err := schema.Fingerprint("CRC-64-AVRO")` 

Both would break the API. Alternatively I can add another function to the schema interface..

**Comment by nrwiersma** [comment]
This obvious issue with having it in one function is they have different byte array outputs, i would imagine. I will think about how we could integrate this, preferably in a less breaky way.

**Comment by nrwiersma** [comment]
So, playing with it a little, i would sway to using a separate function. The `Fingerprint` function is cached as it is using for schema decoder caching, and I dont think the various other fingerprints need this. I would propose something like the following:
```
// FingerprintType is a fingerprinting algorithm.
type FingerprintType string

// Fingerprint type constants.
const (
	CRC64Avro FingerprintType = "CRC64-AVRO"
	MD5       FingerprintType = "MD5"
	SHA256    FingerprintType = "SHA256"
)

type Schema interface {
    ...

    // FingerprintUsing returns the fingerprint using the given algorithm or an error.
    FingerprintUsing(f FingerprintType) ([]byte, error)
}
```

How does that seem? Would love some feedback.

**Comment by przemekd** [comment]
I like this idea :+1: I imagine the scenario where caching calculated fingerprints would be beneficial, e.g. CRC64-AVRO fingerprint could be used many times to generate single-object encoded records.

**Comment by nrwiersma** [comment]
Ok, cool. Will keep the caching in mind. I will start putting a branch together. Will get back to you when i have something.

**Comment by nrwiersma** [comment]
I have started getting this going here: https://github.com/hamba/avro/pull/25

Still need to write the hash function for Avro CRC 64 and finish up the tests. Hope to have it done soon.

**Comment by nrwiersma** [comment]
This has been resolve in https://github.com/hamba/avro/releases/tag/v0.6.0. Let me know how it works for you.

**Comment by przemekd** [comment]
Thanks, it works as expected.
