### ISSUE TITLE
Registry.IsRegistered misses SchemaReferences

### ISSUE THREAD

**Issue by deluan** [hamba/avro#221]
As per the [Schema Registry API documentation](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)), the call to `POST /subjects/(string: subject)` used by `IsRegistered` can accept a list of referenced schemas.

This is crucial for my use case, where I have a bunch of schemas with references, and I need to get the ID of the schemas using IsReferences.

Not sure what to do with the breaking  change (backward compatibility), though. Thoughts?

**Comment by nrwiersma** [comment]
You can make a new function `IsRegisteredWithRefs` that takes the references. At the next major version they can be combined.

**Comment by deluan** [comment]
Hey @nrwiersma , sorry for commenting on a closed issue, but thinking about this a bit more, I think it would be better for the `IsRegisteredWithRefs` return a SchemaInfo, as the Version field is needed to build the references used to query schemas that need them. Example:

I have two schemas:
- `example.Money`
- `example.Tax` (references `example.Money`)

At startup, I need to get the ID of `example.Tax`, so I can publish messages to Kafka with the correct SchemaID. What I'm thinking is:
1. Get the `SchemaInfo` for `example.Money`, using `IsRegisteredWithRefs`. 
2. Build the `registry.SchemaReference` for `example.Money`
3. Get the `ID` for `example.Tax` using the reference above.

As you can see, I would need the `SchemaInfo` for `example.Money` to get the `Version` required to build a `registry.SchemaReference` for it.

Is there any other way to accomplish this? If not, is it ok for me to submit another PR changing the `IsRegisteredWithRefs` to return `(SchemaInfo, error)`?

**Comment by nrwiersma** [comment]
I would suggest you either make a fork or new repo for the registry. I have not intention of making a new major version, and definitely not for the registry client.
