### ISSUE TITLE
Additional Field with default with an old OCF file

### ISSUE THREAD

**Issue by bjet007** [hamba/avro#225]
Hi I was trying to see if we could use your library to store and read avro backup file and it seem that there is a small discrepancy between the behaviour of the `avro.Unmarshal` and the `ocf.Decoder` when reading an "old" avro file with generated code that have a new field.

The scenario that i was trying to achieve is almost the same as the one describe in this ticket https://github.com/hamba/avro/issues/145, but saving the data through a file instead. 

Given the fact that the `readHeader` function is private I don't think I can  create the `ocf.Decoder` myself and pass my new schema ?  

```
package main

import (
	"bytes"
	"fmt"
	"log"
	"strings"

	"github.com/hamba/avro/v2/ocf"
)

const (
	schemaSimpleRecord = `{
    "type": "record",
    "name": "simple",
    "namespace": "org.hamba.event",
    "fields" : [
 		{"name": "a", "type": "string"}
    ]
}`
	schemaSimpleRecordUpdated = `{
    "type": "record",
    "name": "simple",
    "namespace": "org.hamba.event",
    "fields" : [
 		{"name": "a", "type": "string"},
        {"name": "b", "type": "string", "default": "some value"}
    ]
}`
)

type SimpleRecord struct {
	A string `avro:"a"`
}

type SimpleRecordUpdated struct {
	A string `avro:"a"`
	B string `avro:"b"`
}

func main() {

	sourceEvent := &SimpleRecord{
		A: "a",
	}
	var myFile bytes.Buffer

	// We save the file
	writer, _ := ocf.NewEncoder(schemaSimpleRecord, &myFile)

	_ = writer.Encode(sourceEvent)
	_ = writer.Flush()
	_ = writer.Close()

	// We read the file with the latest version of the schema

	fileReader := strings.NewReader(myFile.String())
	// I can't pass the updated schema while creating the decoder
	reader, _ := ocf.NewDecoder(fileReader)
	for reader.HasNext() {
		var record SimpleRecordUpdated

		err := reader.Decode(&record)
		if err != nil {
			log.Fatal(err)
		}
		// Here I would expect that the b field get populated with the default value.
		fmt.Println(record)
	}

}
```

**Comment by nrwiersma** [comment]
Hi, You could not read the old data with the new schema, it would literally not be possible. When writing the data, all fields in the schema must have a value written, and this is assumed (by the spec) when reading. 

If you could switch the schema, very bad things would happen. The difference with the issue you are referring to is they did not change the schema, and this is why it works.

**Comment by bjet007** [comment]
Right that make sense. I  forgot the the schema serialize the content in a specific order when I was trying to test an evolution of my schema .  I guess using nullable would be better than using the default in that specific scenario like I do usually. 

Thanks for you quick answer.
