### ISSUE TITLE
avrogen does not work for union with defined record type

### ISSUE THREAD

**Issue by JuniusLuo** [hamba/avro#226]
Hi,

I hit a problem to define the complex record type in union. A simple example.

Define a record type in uniontype.asvc, `avrogen -pkg test -o uniontype.go uniontype.avsc` works well and generates uniontype.go
{
        "namespace": "test",
        "type": "record",
        "name": "TestUnionType",
        "fields": [
                {"name" : "Field1", "type" : "long"},
                {"name" : "Field2", "type" : "int"}
        ]
}

then define another testmain.avsc, `avrogen -pkg test -o testmain.go testmain.avsc` hits error: "avro: unknown type: TestUnionType"
{
        "namespace": "test",
        "type": "record",
        "name": "TestMain",
        "fields": [
                {"name": "TestUnion", "type": ["null", "TestUnionType"], "default": "null"}
        ]
}

one way to workaround is to use "bytes", and marshal bytes to TestUnionType. Wondering if there is any other way. Or I missed something. Any idea? Thanks!

**Comment by nrwiersma** [comment]
The issue is the schema parser, it cannot work out what `TestUnionType` is. To make this possible, it needs to allow multiple schemas to be generated at the same time.

**Comment by JuniusLuo** [comment]
Thanks @nrwiersma ! Not sure if the schema parser needs to generate multiple schemas at the same time. Could the parser look up whether `TestUnionType` exists in the namespace?

**Comment by nrwiersma** [comment]
Not without knowing about the schema first, and having parsed it.

**Comment by JuniusLuo** [comment]
Got it. Do we plan to support generating multiple schemas at the same time?

**Comment by nrwiersma** [comment]
Seems like it should be possible.
