### ISSUE TITLE
Registry compatibility levels

### ISSUE THREAD

**Issue by nucccc** [hamba/avro#228]
Good afternoon,
the confluent registry API provides a pair of functionalities to set the compatibility level of a subject, as described in the [API](https://github.com/nucccc/avro/tree/registry_compatibility_level). Years ago I wrote code for such stuff, now if these functionalities are of interest I would like to contribute to the project.

I started writing some code for that inmy fork at [this branch](https://github.com/nucccc/avro/tree/registry_compatibility_level). If you can, please let me know if the feature would be of interest for the project and what would be required for a pull request.

Thanks in advance for the attention,
Nuc

Edit: PS: And thanks for the great library!!!

**Comment by nrwiersma** [comment]
Hi,

You are welcome to contribute the code if you find it useful and think others will too. It will however need changes to pass review, but given that, should you wish to contribute, that would be great.
