### ISSUE TITLE
Support for Avro logical type `duration`

### ISSUE THREAD

**Issue by mibanescu** [hamba/avro#231]
I was pleasantly surprised to notice that the library will correctly map the `duration` Avro logical type to a `time.Duration` in go.

However, I ran into issues with codecs not handling the underlying int64 (which `time.Duration` is) in relation to the `fixed` type (which is what Avro uses internally).

I proceeded to add that, until I ran into issues converting the number of months to a number of nanoseconds.

The Avro specs do mention:

```
The duration logical type represents an amount of time defined by a number of months, days and milliseconds. This is not equivalent to a number of milliseconds, because, depending on the moment in time from which the duration is measured, the number of days in the month and number of milliseconds in a day may differ. Other standard periods such as years, quarters, hours and minutes can be expressed through these basic periods.
```

My proposal would be to create a new data type `avro.Duration` that stores months, hours and milliseconds as `uint32`, and doesn't try to do any type of conversion, since that's where madness starts.

I will be happy to take a stab at a PR if this sounds reasonable.

Note: I grepped the Avro git repo for any kind of usage of `duration`. Most implementations don't even support it. Rust seems to try but keeps it as 3 different fields, as far as I can tell.

**Comment by nrwiersma** [comment]
Hi,

You are correct that this was never implemented because of the issues you have faced. I think your proposed solution is good, and I would happily take a PR implementing this.
