### ISSUE TITLE
Codecs for microtypes

### ISSUE THREAD

**Issue by lucastorri** [hamba/avro#234]
Hi All and thank you for this library!

We recently started to use this library and were quite happy with the overall result. However, one thing that we missed was the ability to handle go microtypes. For instance, for most of the entities in our service we define types instead of using primitives:

```go
type OrderID string

type Order {
  ID OrderID
}
```

This is a bit unfortunate, because when using the generated struct we end up having to cast all those microtypes.

With that, we decided to create our own generator and for an input like:

```avdl
record Something {
  @go-type("primitives.OrderID") string orderId;
}
```

which translates to:

```json
{
  "type" : "record",
  "name" : "Something",
  "fields" : [ {
    "name" : "orderId",
    "type" : {
      "type" : "string",
      "go-type" : "primitives.OrderID"
    }
  } ],
  "tags" : [ "generate" ]
}
```

we now end up with a code like:

```go
type Something {
  ID primitives.OrderID
}
```

That is all nice and well, but when trying to encode/decode data, we end up with an error:

> ID: avro: primitives.OrderID is unsupported for Avro string

Looking at this library's `API` type, we couldn't find any method to register a custom codec or tell the library that `OrderID` is indeed a string. Do you know if there is any workaround we can try out?

Thank you once again!

**Comment by nrwiersma** [comment]
Hi,

You will need to provide some code, as I cannot produce this error. The following is a working example:

prim/prim.go
```
package prim

type TN string

type TI int
```

main,go
```
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/hamba/avro/v2"
	"github.com/nrwiersma/test/avro/prim"
)

var schema = avro.MustParse(`{
    "type": "record",
    "name": "test",
    "namespace": "test",
    "doc": "docstring",
	"fields": [
		{ "name": "name","type": "string" },
		{ "name": "num","type": "int" },
		{ "name": "test_time","type": {"logicalType": "timestamp-micros", "type": "long"}}
	]
}`)

type MyRecord struct {
	Name     prim.TN   `avro:"name"`
	Num      prim.TI   `avro:"num"`
	TestTime time.Time `avro:"test_time"`
}

func main() {
	record := MyRecord{
		Name:     "test-name",
		Num:      21,
		TestTime: time.Now(),
	}
	b, err := avro.Marshal(schema, record)
	if err != nil {
		log.Fatal(err)
	}

	var got MyRecord
	err = avro.Unmarshal(schema, b, &got)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(got)
}
```

Output:
```
{test-name 21 2023-02-07 17:59:05.619898 +0000 UTC}
```

**Comment by lucastorri** [comment]
Yes, indeed! Thanks a lot for checking @nrwiersma and sorry about the inconvenience.

After your test, I double-checked mine and saw that I was wrongly trying to use and `int` type against a primitive that was in fact a `float64`. My mistake!

Thanks once again!
