### ISSUE TITLE
Example of writing an avro file containing a sequence of records

### ISSUE THREAD

**Issue by alexflint** [hamba/avro#243]
Is there an example of writing a series of Go structs to an avro file? I have a Go struct with the required struct tags, and an avro schema that parses correctly, and I can encode individual structs to avro files, but I want to produce an avro file containing a sequence of records. I have the sense that I need to use OCFWriter -- is that correct?

I went through the examples directory but didn't find any examples of this.

**Comment by nrwiersma** [comment]
I assume this answered your question. If you have further questions you are welcome to reopen the issue.
