### ISSUE TITLE
PropertySchema properties are not JSON marshalled/unmarshalled

### ISSUE THREAD

**Issue by jacobmarble** [hamba/avro#275]
## Problem

I'm working with the Apache Iceberg project, which uses Avro to store certain metadata. The spec [requires the use of certain properties in the Avro schema](https://iceberg.apache.org/spec/#avro). It looks like this package doesn't consider properties for JSON serialization.

## Proposal 1

I propose this pattern be applied to *most* implementations of `PropertySchema`. It appears that deserialization is already working, at least in the one or two places I checked.

```diff
--- a/schema.go
+++ b/schema.go
@@ -643,36 +643,26 @@ func (f *Field) String() string {
 
 // MarshalJSON marshals the schema to json.
 func (f *Field) MarshalJSON() ([]byte, error) {
-	type base struct {
-		Name    string   `json:"name"`
-		Aliases []string `json:"aliases,omitempty"`
-		Doc     string   `json:"doc,omitempty"`
-		Type    Schema   `json:"type"`
-		Order   string   `json:"order,omitempty"`
- 	}
-	type ext struct {
-		base
-		Default any `json:"default"`
- 	}
-
-	b := base{
-		Name:    f.name,
-		Aliases: f.aliases,
-		Doc:     f.doc,
-		Type:    f.typ,
-	if f.doc != "" {
-		m["doc"] = f.doc
-	}
-	if f.order != Asc {
-		b.Order = string(f.order)
- 	}
-
-	var s any = b
- 	if f.hasDef {
-		s = ext{
-			base:    s.(base),
-			Default: f.Default(),
-		}
- 	}
-	return jsoniter.Marshal(s)
+	m := make(map[string]any, len(f.props)+2)
+	for k, v := range f.props {
+		// set properties first so that they can be overridden
+		m[k] = v
+	}
+	m["type"] = f.typ
+	m["name"] = f.name
+	if f.aliases != nil {
+		m["aliases"] = f.aliases
+	}
+	if f.doc != "" {
+		m["doc"] = f.doc
+	}
+	if f.order != Asc {
+		m["order"] = string(f.order)
+	}
+	if f.hasDef {
+		m["default"] = f.Default()
+	}
+	return jsoniter.Marshal(m)
 }
 
 // EnumSchema is an Avro enum type schema.
```

## Proposal 2

I propose that `ocf.NewEncoder()` fill the `avro.schema` metadata value using the result of `schema.MarshalJSON()` instead of `schema.String()`.

The way `ocf.NewEncoder()` handles the schema is a little confusing:
- arg `s string` is a stringified schema: https://github.com/hamba/avro/blob/b4a402f41cf44b6094b5131286830ba9bb1eb290/ocf/ocf.go#L214
- `s` is parsed to `schema avro.Schema`: https://github.com/hamba/avro/blob/b4a402f41cf44b6094b5131286830ba9bb1eb290/ocf/ocf.go#L259
- `schema` converted back to a string, using the `.String()` method, for the `avro.schema` metadata value: https://github.com/hamba/avro/blob/b4a402f41cf44b6094b5131286830ba9bb1eb290/ocf/ocf.go#L264

`.String()` isn't the same as `.MarshalJSON()`, and I'm not sure what its purpose is. It seems the convention in this package is to look like JSON, but not completely.

According to [the Avro Spec v1.11.1](https://avro.apache.org/docs/1.11.1/specification/#object-container-files):
> **avro.schema** contains the schema of objects stored in the file, as JSON data (required).

**Comment by nrwiersma** [comment]
Proposal 1:

Sure, props can be included, but your proposed solution has an issue in that maps are not ordered and so the output of the JSON may not be constant (comparable as a string), which would not be great.

Proposal 2:

> The way ocf.NewEncoder() handles the schema is a little confusing:

It is parsed as it needs a schema object to encode and to know the passed string is actually a schema. It is re-encoded to be sure there is nothing random in the initial string that could be a security issue.

> .String() isn't the same as .MarshalJSON(), and I'm not sure what its purpose is. It seems the convention in this package is to look like JSON, but not completely.

`.String()` returns the [canonical schema ](https://avro.apache.org/docs/1.11.1/specification/#parsing-canonical-form-for-schemas) which is needed for schema resolution. While not specifically stated, it is the minimal form of schema needed for reading, which is why it was chosen.

I have no issue with using the JSON form as long as it is constant, but to not make this a breaking change, I think it should be configurable.

**Comment by jacobmarble** [comment]
Everything you said makes sense. Thank you for the link about "Parsing Canonical Form", it clarifies a lot. I understand why the JSON and canonical forms are not treated the same way.

> your proposed solution has an issue in that maps are not ordered and so the output of the JSON may not be constant (comparable as a string), which would not be great.

If we continue using Parsing Canonical Form in `ocf.NewEncoder()`, then does deterministic JSON key ordering matter in the JSON form? If the difference is in unit tests, then I can adjust those.

> > The way ocf.NewEncoder() handles the schema is a little confusing:
>
> It is parsed as it needs a schema object to encode and to know the passed string is actually a schema. It is re-encoded to be sure there is nothing random in the initial string that could be a security issue.

Makes sense.

> .String() returns the [canonical schema ](https://avro.apache.org/docs/1.11.1/specification/#parsing-canonical-form-for-schemas) which is needed for schema resolution. While not specifically stated, it is the minimal form of schema needed for reading, which is why it was chosen.

This is interesting because the Apache Iceberg reference implementation (Java) generates Avro files that include `doc` attributes, which are explicitly named as to be stripped in [Transforming into Parsing Canonical Form](https://avro.apache.org/docs/1.11.1/specification/#transforming-into-parsing-canonical-form).

## New Proposal 1

In JSON form, always emit all attributes, including properties, `doc`, `aliases`.

Do not worry about JSON field ordering in JSON form.

## New Proposal 2

In Parsing Canonical Form, add properties to the output, and make the property output optional, defaulting to not including properties.

**Comment by nrwiersma** [comment]
> In JSON form, always emit all attributes, including properties, doc, aliases.

This makes sense. I would still prefer this to be ordered.

> In Parsing Canonical Form, add properties to the output

This is a no go. From the spec, this form cannot contain other fields other than those specified in `[STRIP]`. It also has implications on the schema fingerprint.

**Comment by jacobmarble** [comment]
I'll work on the JSON form proposal, with deterministic ordering.
