### ISSUE TITLE
Support for time.Time format (Logical types)

### ISSUE THREAD

**Issue by mscno** [hamba/avro#29]
Hi,

First of all thanks for a great, and simple to use avro serializer/deserializer for go!
It works great for our current streaming applications.

I'm just curious to know if you have adding support for go's `time.Time` struct in the pipeline?

Currently I am adding a step where I convert `time.Time` to epoch time saved in `int64` (Go) and  `long` (avro). But this entails adding extra steps and structs in my Go code.

Again, thanks for a great avro parser!

Best Mads

**Comment by nrwiersma** [comment]
Hi, Thanks very much.

Logical types are definitely on the TODO list, I have just not had time to get there yet. I had originally started avro PRC first, but this is relatively complex.

I cannot give you a date, but i hope to start working on this soon.

Thanks,
Nick

**Comment by mscno** [comment]
Hi Nick,
Thanks for the quick reply, I was just curious, and wanted to give you a heads up and kudos for the work so far!

Mads

**Comment by sneko** [comment]
Hi @nrwiersma ,

Any news on that? Would be really useful in addition to the rest (BTW, really good job)  🎉

**Comment by nrwiersma** [comment]
Hey,

I have started, and have a fair bit of the schema integration worked out. But with the festive season and going back to work, in short, madness ensued. I am hoping to get back to it in a couple weeks when everything calms down a bit.

Sorry for the delay in this.

**Comment by nrwiersma** [comment]
So just an update on whats been going on.

After a couple false starts, I have the schema and parsing of the schema done. Next I will add encoding then decoding.

You can track progress on this [branch](https://github.com/hamba/avro/tree/logical-types)
