### ISSUE TITLE
Unmarshaling Interface Types in a Union

### ISSUE THREAD

**Issue by tylerwendell** [hamba/avro#299]
### Description:
I've come across an issue while working with the Avro library that involves unmarshaling interface types in a union. I'll provide a clear scenario and code examples to illustrate the problem.

### Scenario:
In my play code, I'm attempting to unmarshal Avro bytes into a Go struct. The Avro schema includes a union type with possible interface implementations. The library allows for the marshaling of such structures, but I encountered a fatal error when trying to unmarshal the data back into the struct.

There seems to be a couple of issues related to this in the past but I would love to verify that I am not doing something incorrectly. It seems weird that it works in the marshaling direction and not the unmarshaling direction. 

 I see in the doc:
> The following union types are accepted: map[string]any, *T and any.

### Simple Example:
I have defined a schema that involves a Person struct with a Transportation interface, which can be one of several implementing types: Car, Bike, or Boat. The relevant code snippet is as follows:
```go
package main

import (
	"log"

	"github.com/hamba/avro/v2"
)

var (
	PersonJSON = `{
	"type": "record",
	"name": "person",
	"namespace": "schema",
	"fields": [
		{ "name": "Name", "type": "string" }, 
		{ "name": "Transportation", "type": [
				"schema.car",
				"schema.bike",
				"schema.boat"
			]
		}
	]
}`
	CarJson = `{
	"type": "record",
	"name": "car",
	"namespace": "schema",
	"fields": [
		{ "name": "Make", "type": "string" }, 
		{ "name": "Model", "type": "string" }, 
		{ "name": "Wheels", "type": "int" }
	]
}`

	BoatJson = `{
	"type": "record",
	"name": "boat",
	"namespace": "schema",
	"fields": [
		{ "name": "Wheels", "type": "int" }
	]
}`

	BikeJSON = `{
	"type": "record",
	"name": "bike",
	"namespace": "schema",
	"fields": [
		{ "name": "Sails", "type": "int" }, 
		{ "name": "Wheels", "type": "int" }
	]
}`
)

type Person struct {
	Name           string         `avro:"Name"`
	Transportation Transportation `avro:"Transportation"`
}

type Transportation interface {
	NumWheels() int
}

type Car struct {
	Make   string `avro:"Make"`
	Model  string `avro:"Model"`
	Wheels int    `avro:"Wheels"`
}

type Bike struct {
	Wheels int `avro:"Wheels"`
}

type Boat struct {
	Wheels int `avro:"Wheels"`
	Sails  int `avro:"Sails"`
}

func (c Car) NumWheels() int { return c.Wheels }

func (b Bike) NumWheels() int { return b.Wheels }

func (b Boat) NumWheels() int { return b.Wheels }

func main() {
	avro.Register("schema.car", Car{})
	avro.Register("schema.bike", Bike{})
	avro.Register("schema.boat", Boat{})

	for _, json := range []string{BikeJSON, CarJson, BoatJson} {
		_ = parse(json)
	}

	personSchema := parse(PersonJSON)
	p1 := &Person{
		Name:           "Tim",
		Transportation: Boat{Wheels: 0, Sails: 1},
	}

	data, err := avro.Marshal(personSchema, p1)
	if err != nil {
		log.Fatalf("%v", err)
	}

	var p Person
	if err = avro.Unmarshal(personSchema, data, &p); err != nil {
		log.Fatalf("%v", err)
	}
}

func parse(json string) avro.Schema {
	schema, err := avro.Parse(json)
	if err != nil {
		log.Fatalf("Failed to Parse: %s", err)
	}
	return schema
}
```

I hit a fatal error only when I tried to unmarshal what I just marshaled. I get the error:
`Transportation: avro: main.Transportation is unsupported for Avro union`

### Desired Solution:
I would prefer not to resort to using the `any` type for `Person.Transportation` in order to maintain type safety. It would be great if the library could support unmarshaling of interface types within unions, as it already works for the marshaling process. I could be doing something wrong in my code, and I would love it if that were the case. If not, what are the chances it could be added to the library?

**Comment by tylerwendell** [comment]
I have been trying to step through the code and figure out how to make it work and I cannot see how to make it work either. Thanks for the quick response. Ill close.

**Comment by nrwiersma** [comment]
I literally spend 3 hours to try get the initial interface type to accept a new pointer, but to no avail.

**Comment by tylerwendell** [comment]
There isn't a single go avro library that makes it work. A lot of them won't even marshal union types.

**Comment by pckhoi** [comment]
Sorry but I don't understand why decoder couldn't be made to work. The decoder could treat interface receivers in this way:

1. Inspect the data and figure out the name of the concrete avro type
2. Look up the registered Go type under that name. If not found, fallback to the old implementation
3. Check if the registered Go type fulfill the given interface, if not return an error
4. Decode the data into the registered Go type and profit

Unless there's something else I'm not understanding.

**Comment by nrwiersma** [comment]
Interface types (iface) are not createable in Go, you are only able to covert a concrete into an iface type. In reflect this possible, but using rtypes and unsafe pointers, there is no mechanism to do this.

Getting the concrete is not an issue, but as the interface is nil, there is no way to get the value out again.
