### ISSUE TITLE
Add protocol original schema string

### ISSUE THREAD

**Issue by EliaBracciSumo** [hamba/avro#317]
I would like to add also another field in Protocol struct. Here the [PR](https://github.com/hamba/avro/pull/316/).

I called it OriginalString but we can change it. The intent is to save the string of the protocol as is, using its non-canonical form. WDYT?

I need this to generate Protocol hash.

cc: @nrwiersma

**Comment by EliaBracciSumo** [comment]
Thank you for your feedback. Yes, this is what I'm doing right now. My intent was to see if I'm the only one with this kind of "issue". We can close the issue if you want 👍

**Comment by nrwiersma** [comment]
The hash you need is non-spec, from my reading. The hash of the protocol is meant to be used in the protocol wire format, which should be of the canonical.

I dont know what you need the non-canonical hash for, but I prefer to keep this module based around specs.

**Comment by EliaBracciSumo** [comment]
I agree with you 👍  I'll close the issue, thank you 🙏
