### ISSUE TITLE
Infinite loop parsing recursive schema

### ISSUE THREAD

**Issue by EliaBracciSumo** [hamba/avro#318]
Hi, starting from version 2.15.0, I'm having issues parsing recursive schema (Union type). It works until version 2.14.0 but from higher version, it enters an infinte loop between lines github.com/hamba/avro/v2@v2.15.0/schema_walk.go:17 and github.com/hamba/avro/v2@v2.15.0/schema_walk.go:9

Replication schemas:

```
{
    "type" : "record",
    "name" : "SuperPower",
    "fields" : [ {
      "name" : "power",
      "type" : [ "null", "SuperPower" ],
      "default" : null
    } ]
  }
```

```
{
    "type" : "record",
    "name" : "SuperHero",
    "fields" : [ {
      "name" : "superPower",
      "type" : [ "null", "SuperPower" ]
    }]
  }
```

**Comment by nrwiersma** [comment]
Fixed in [v2.17.1](https://github.com/hamba/avro/releases/tag/v2.17.1). Thanks for reporting.
