### ISSUE TITLE
Support TextMarshaler/TextUnmarshaler for map keys

### ISSUE THREAD

**Issue by stampy88** [hamba/avro#327]
Hi,

I realize that Avro doesn't support non-string keys for maps, but it would be very useful to be able to have something in the Go space that isn't a string, but supports the `TextMarshaler/TextUnmarshaler` that allows it to turn itself into a string for serialization purposes for maps in Avro. What do you think?

**Comment by nrwiersma** [comment]
Technically it is feasible. I would keep it as a separate case from the standard string key en/decode case, as it would have a performance impact calling the functions.

**Comment by stampy88** [comment]
Thanks @nrwiersma!
