### ISSUE TITLE
[BUG] array schema cannot be correctly parsed

### ISSUE THREAD

**Issue by 3AceShowHand** [hamba/avro#337]
```
schema := `{
		"type": "record",
		"name": "simple",
		"namespace": "org.hamba.avro",
		"fields" : [
			{"name": "a", "type": "long"},
			{"name": "b", "type": "string"},
			{"name": "c", "type": "array", "items": "string"}
		]
	}`

	avroSchema, err := avro.Parse(schema)
	require.NoError(t, err)
	require.NotNil(t, avroSchema)
```

This unit test cannot pass, and return `avro: unknown type: array`

IMHO, this schema should be parsed into Schema correctly, with no error returned, since this is achieved by using other golang Avro implementations.

Is there anything wrong with the schema or the parser code ?

**Comment by nrwiersma** [comment]
`{"name": "c", "type": "array", "items": "string"}`

This is incorrect.

**Comment by 3AceShowHand** [comment]
> `{"name": "c", "type": "array", "items": "string"}`
> 
> This is incorrect.

Can you give me some hint about the correct schema declaration? This can be correctly parsed by using `linkedin/goavro/v2`, so I thought it's correct.

I also found that in the `encoder_array_test.go` file, there is one test named `TestEncoder_Array`, it's schema is declared as `{"type":"array", "items": "int"}`, this looks the same as `{"name": "c", "type": "array", "items": "string"}`.

**Comment by nrwiersma** [comment]
You are confusing the field and the array type:
```
{"name": "c", "type": {"type":"array", "items": "int"}}
```

**Comment by 3AceShowHand** [comment]
The issue is resolved, and close this
