### ISSUE TITLE
Local timestamp logical types

### ISSUE THREAD

**Issue by victoraugustolls** [hamba/avro#338]
Hey! Thanks for this amazing package!

I was wondering if it would be possible to implement the following logical types:
- local-timestamp-millis
- local-timestamp-micros

If not, would you be willing to accept pull requests for it? Thanks!

**Comment by nrwiersma** [comment]
Hi.

They should be reasonably simple to implement, but there is a large PR open at the moment that needs to be merged first. It seems like something that can be tackled soon though.

PRs are always welcome, but no guarantees on being merged.
