### ISSUE TITLE
Question about max byte slice

### ISSUE THREAD

**Issue by torwig** [hamba/avro#341]
Hi, I see the following comment (https://github.com/hamba/avro/blob/main/config.go#L49C10-L49C10)
```
// MaxByteSliceSize is the maximum size of `bytes` or `string` types the Reader will create, defaulting to 1MiB.
// If this size is exceeded, the Reader returns an error. This can be disabled by setting a negative number.
MaxByteSliceSize int
```
And the function here (https://github.com/hamba/avro/blob/main/config.go#L49C10-L49C10):
```
func (c *frozenConfig) getMaxByteSliceSize() int {
	size := c.config.MaxByteSliceSize
	if size == 0 {
		return maxByteSliceSize
	}
	return size
}
```

And here we have a constant (https://github.com/hamba/avro/blob/main/config.go#L10C1-L11C37):
`const maxByteSliceSize = 1024 * 1024`

My question is: 1024*1024 it's not equal to 1 MiB. Is there a typo in the configuration parameter or typo in the `maxByteSliceSize` value? Or there is somewhere multiplication by 1024 before using it? 

BTW, here (https://github.com/hamba/avro/blob/main/reader.go#L227) I see the usage of the function as is, without any multiplication:
```   
        size := int(r.ReadLong())
   .................
        if max := r.cfg.getMaxByteSliceSize(); max > 0 && size > max {
		fnName := "Read" + strings.ToTitle(op)
		r.ReportError(fnName, "size is greater than `Config.MaxByteSliceSize`")
		return nil
	}
```

Or `ReadLong` gets the size in kilobytes?

Thank you for any explanation.

**Comment by nrwiersma** [comment]
This is a bug in `maxByteSliceSize`. Thanks for catching this.

**Comment by hhromic** [comment]
> My question is: 1024*1024 it's not equal to 1 MiB. Is there a typo in the configuration parameter or typo in the `maxByteSliceSize` value? Or there is somewhere multiplication by 1024 before using it?

I know this was recently fixed, but I got very curious about this statement. To my understanding, 1024*1024 _is_ equal to [1 MiB](https://en.wikipedia.org/wiki/Byte#Multiple-byte_units). The PR fixing this replaced `1024*1024` with `1_048_576`, but both expressions are equal.
```go
fmt.Println(1024*1024 == 1_048_576)
// Output: true
```
So, I can't wrap my head around what was fixed by it 🙈.

**Comment by torwig** [comment]
My apologies, gentlemen.

**Comment by nrwiersma** [comment]
No harm no foul. i could have scrutinised this more, but didn't.
