### ISSUE TITLE
"unknown union type long" error

### ISSUE THREAD

**Issue by kesmit13** [hamba/avro#366]
I'm working on a project that uses timestamp-micros fields that are nullable. My Avro schema has a field with the following form:
```
{"name": "event_time", "type": ["null", {"type": "long", "logicalType": "timestamp-micros"}]}
```

When I attempt to marshal an int64 into that value I get the following error:
```
avro: unknown union type long
```

If I remove the null from the union type, it works fine. The data I'm marshaling is a `map[string]interface{}` which contains either an int64 value or a nil. I'm not sure what needs to be changed to make this work.

**Comment by nrwiersma** [comment]
As shown in the [README](https://github.com/hamba/avro?tab=readme-ov-file#types-conversions), logic type `timestamp-micros` maps to a `time.Time`. Remove the logic type and it will encode as you expect.

**Comment by kesmit13** [comment]
Ah, I see now. Or I could change the value in the map to a `time.Time` and keep the schema the same. Thanks.
