### ISSUE TITLE
Problem with empty slices vs nil.

### ISSUE THREAD

**Issue by oderwat** [hamba/avro#371]
When using a `[]byte` in a struct and doing a marshal / unmarschal with a nil value in `[]byte` it is changed to an empty slice. Should []byte (aka []uint8) not be supported for Avro union (`["null", "bytes"]`), so we can keep the difference between the nil and the empty slice?

**Comment by oderwat** [comment]
No this is not a `*[]byte` "needed" and I think that would be something different too (a pointer to a slice). 

`var b []byte // b == nil` while `b:=[]byte{} // b != nil` (see: https://go.dev/play/p/Q4A3D0ChKt6 for some examples).

There are in fact differences:

1. It uses (more) memory for the empty slice, while nil does not. 
2. You can use the nil to check if a slice is initialized (materialized?)
3. It is not equal when you test the marshal/un-marshal of a struct containing a nil '[]byte'.

What you refer to is that both have a length of 0 I think.

**Comment by nrwiersma** [comment]
What is your proposal here?

**Comment by nrwiersma** [comment]
> The current problem for us is that if I have the above union in the schema, I get the '[]uint8 is unsupported for Avro union' error. I think this could be supported and if the value really is nil, the null is used.

This is currently supported using `*[]byte` which is following the convention in the library of `[null, X]` => `*X`. It would be possible to have a special case for slices and maps. Would welcome a PR to that effect.

**Comment by nrwiersma** [comment]
Can you give this branch a try and see if it does what you think it should: https://github.com/hamba/avro/pull/372

**Comment by oderwat** [comment]
Sadly there seems to be a problem with schema validation now. At least I do not understand why this one would be invalid:

```
{
  "type": "record",
  "namespace": "testdata.listv1",
  "name": "ListV1",
  "avrox": "0.1.1",
  "fields": [
    {
      "name": "Magic",
      "type": {
        "name": "avrox_magic_8",
        "size": 8,
        "type": "fixed"
      }
    },
    {
      "name": "Name",
      "type": "string"
    },
    {
      "name": "Items",
      "type": {
        "items": [
          "null",
          {
            "type": "record",
            "name": "ItemV1",
            "avrox": "0.2.1",
            "fields": [
              {
                "name": "Magic",
                "type": {
                  "name": "avrox_magic_8",
                  "size": 8,
                  "type": "fixed"
                }
              },
              {
                "name": "ULID",
                "type": "string"
              },
              {
                "name": "Name",
                "type": "string"
              },
              {
                "name": "Amount",
                "type": "int"
              },
              {
                "name": "Bin",
                "type": [
                  "null",
                  "bytes"
                ]
              },
              {
                "name": "Ints",
                "type": {
                  "items": "int",
                  "type": "array"
                }
              },
              {
                "name": "Floats",
                "type": {
                  "items": "double",
                  "type": "array"
                }
              },
              {
                "name": "Bools",
                "type": {
                  "items": "boolean",
                  "type": "array"
                }
              }
            ]
          }
        ],
        "type": "array"
      }
    }
  ]
}
```

P.S.: The part that makes it not validate with hamba/avro is the one with the union for the bytes. When I make this simply a "bytes" it validates, but then I get the problem with nil != empty slice again.
