### ISSUE TITLE
Reasoning behind swallowing EOF errors?

### ISSUE THREAD

**Issue by brianshih1** [hamba/avro#377]
It looks like the `Decoder` is swallowing `EOF` errors in [this line of code](https://github.com/hamba/avro/blob/b43fe48eef0167a038bc192051bce6fcfc8be56e/decoder.go#L39). I would like to understand the reasoning behind that.

In the example below, I am trying to decode an `array of boolean` with an invalid data (contains an encoded `long` but no data for the boolean). I was expecting it to error out as we are dealing with invalid input but the `EOF` error is swallowed so the following test fails.

```
func TestDecoder_ArrayEof(t *testing.T) {
	// 10 (long) gets encoded to 0x14
	data := []byte{0x14}
	schema := `{"type":"array", "items": { "type": "boolean" }}`
	dec, err := avro.NewDecoder(schema, bytes.NewReader(data))
	require.NoError(t, err)

	var got []bool
	err = dec.Decode(&got)

	assert.Error(t, err)
}
```

I tested out commenting out the predicate:
```
if errors.Is(d.r.Error, io.EOF) {
  return nil
}
```
and it causes these two tests to fail: `TestDecoder_SkipRef`, `TestDecoder_DecodeEOFDoesntReturnError`.

If I need a way to access these `eof` errors, what might be the best way to do that? Perhaps we can expose an `IsEof` method for the decoder?

**Comment by nrwiersma** [comment]
I think the line you are pointing to is a bug introduced with the switch to `errors.Is` and `errors.As`. 

The intention here is to swallow direct `io.EOF` errors, not wrapped `io.EOF` errors. `io.EOF` is a strange error in that it does not directly indicate an error, just the end of the stream. If data is actually missing, the mod should always return an error other than `io.EOF` (but likely always wrapping it). This makes direct `io.EOF` errors non-errors, and therefore not an error.

**Comment by brianshih1** [comment]
thanks for explaining it, makes a lot of sense!
