### ISSUE TITLE
[avrogen] tags - having omitEmpty in the json generated object

### ISSUE THREAD

**Issue by adrianiacobghiula** [hamba/avro#391]
Assuming one might want to add the json tag to the generated objects one can easily do it by using `-tags json:original`.

The missing feature is the possibility to add the `omitempty` to the json tag like `json:"phones,omitempty"`

How should the command look like if a feature like this one would be added in the avrogen ?

**Comment by adrianiacobghiula** [comment]
I would say to be as close as possible to the avro serialized data & considering `omitempty` feature in json Marschal I would only add omitempty where in avro a union with "null" existed...
On the other hand there might be other opinions here to add everywhere to completely ignore false bool or empty strings or 0 or empty array slice, map to minimize the output.

**Comment by nrwiersma** [comment]
> I would say to be as close as possible to the avro serialized data & considering omitempty feature in json Marschal I would only add omitempty where in avro a union with "null" existed...

This would require `avrogen` to "know" about the `json` tag, which it does not (well, no more than any other tag). 

> On the other hand there might be other opinions here to add to every single field to completely ignore false bool or empty strings or 0 or empty array slice, map to minimize the output.

`omitempty` is a very specific tag modifier, and as no specific tags are supported, this would need to be more general, like a set of modifiers. The issue I see here is if one was adding 2 tags, 1 that supports `omitempty` and one does not. How would the modifiers be applied, or must they be added per tag. A lot to consider here to make this make sense.

**Comment by adrianiacobghiula** [comment]
I am thinking that the simplest would be to make avrogen "know" about `json` & `omitempty` (as it will only take a few lines of code) and not tackle a general set of modifiers for any possible tag

**Comment by nrwiersma** [comment]
There is an issue with this though. Why support `json` and not `yaml`, and if `yaml` why not `protobuf` or `mapstructure` or any number of other tags, each with their own needs. This, IMO, is the route to a ton of complexity. By keeping things generic we best effort support all tags.

**Comment by adrianiacobghiula** [comment]
allowing to override the template ? or just parts of the template like: more than just `{{ .Tag }}` ?

**Comment by nrwiersma** [comment]
That would be possible, but the entire thing only I think. It would be best for it to take a string or file, the template needed is not small.

**Comment by nrwiersma** [comment]
Closed by #392
