### ISSUE TITLE
Logical Types for Union and ComplexType

### ISSUE THREAD

**Issue by TuSKan** [hamba/avro#41]
First of all, thank you very much for so great package!!! 

I'm having a problem with this schema: 
```
{"type":["null", "int"],"logicalType":"date"}
```
On _parsePrimitive(typ, nil)_ it pass nil for _String, Bytes, Int, Long, Float, Double, Boolean_ so in _parsePrimitiveLogicalType_ it returns _nil_ and don't create the _LogicalType_
It also happens with complex structures, no only with union.

Here is a fail example:
```
func TestEncoder_Time_Date(t *testing.T) {
	defer ConfigTeardown()

	schema := `{"type":["null", "int"],"logicalType":"date"}`
	buf := bytes.NewBuffer([]byte{})
	enc, err := avro.NewEncoder(schema, buf)
	assert.NoError(t, err)

	tm := time.Date(2020, 1, 2, 0, 0, 0, 0, time.UTC)

	err = enc.Encode(&tm)

	assert.NoError(t, err)
	assert.Equal(t, []byte{0xAE, 0x9D, 0x02}, buf.Bytes())
}
```
If you like, i can investigate more and try to propose a PR.

**Comment by nrwiersma** [comment]
Hi,

You cannot have a logical type on a union. You are likely looking for `{"type":["null", {"type":"int","logicalType":"date"}]}`. As noted in the docs `date` is only valid on an `int`, hence `int.date`.

Let me know if that works for you.

**Comment by TuSKan** [comment]
This should be worked?

```
func TestDateEncode(t *testing.T) {
	schema := `{
				"doc": "blablabla",
				"namespace": "ns",
				"name": "date",
				"type": "record",
				"fields": [
					{
						"name": "dt",
						"type": "int",
						"logicalType": "date"
					}
				]
			}`
	buf := bytes.NewBuffer([]byte{})
	enc, err := avro.NewEncoder(schema, buf)
	assert.NoError(t, err)
	type Date struct{ dt time.Time }
	tm := Date{dt: time.Date(2020, 1, 2, 0, 0, 0, 0, time.UTC)}
	err = enc.Encode(&tm)

	assert.NoError(t, err)
	assert.Equal(t, []byte{0xAE, 0x9D, 0x02}, buf.Bytes())
}
```
Error:      	Received unexpected error:
        	dt: avro: time.Time is unsupported for Avro int

**Comment by nrwiersma** [comment]
No, it shouldnt, you are adding the logical type to the field and not the int. You want:
```
{
				"doc": "blablabla",
				"namespace": "ns",
				"name": "date",
				"type": "record",
				"fields": [
					{
						"name": "dt",
						"type": {"type":"int","logicalType": "date"}
					}
				]
			}
```

**Comment by TuSKan** [comment]
It works!!!  
Thank you very much for been so kindly and teach me how to use logicalType.
:)
