### ISSUE TITLE
Improve zstd encoder and decoder usage in the compressor codec

### ISSUE THREAD

**Issue by bignacio** [hamba/avro#419]
The ocf compressor codec creates a new zstd encoder and decoder for each call to Encode and Decode, which can results in a large number of memory allocations and impact to CPU usage.

The [klauspost/compress library](https://github.com/klauspost/compress/tree/master/zstd#usage) documents that encoders and decoders can be created once and reused many times after a reset, avoiding new allocations

**Comment by nrwiersma** [comment]
Fixed by #420
