### ISSUE TITLE
Issue decoding fixed decimal field into *big.Rat

### ISSUE THREAD

**Issue by cdrexle** [hamba/avro#424]
When encoding a fixed decimal field, the source data type is required to be *big.Rat (see https://github.com/hamba/avro/blob/v2.23.0/codec_fixed.go#L76), but when decoding, only big.Rat is supported (see https://github.com/hamba/avro/blob/v2.23.0/codec_fixed.go#L40).

This causes an issue when trying to encode and decode using the same struct, as it will be incompatible and not have the ability to decode into the same type that it encoded from.

The tests that cover this scenario (here https://github.com/hamba/avro/blob/v2.23.0/decoder_fixed_test.go#L43) don't correctly pass in the destination object, since Decode requires a pointer to where we want to store the data. Since we want to store in a *big.Rat (as that's what we encoded from), we need to pass in a **big.Rat.

**Comment by nrwiersma** [comment]
Would it be possible for you to test this branch: https://github.com/hamba/avro/tree/fix-big-rat

**Comment by cdrexle** [comment]
Thanks for the quick response! Yes that fixed the issue :+1: I was working on a PR myself that was pretty much what you have here

**Comment by nrwiersma** [comment]
Out of interest, is this being testing in a production like workload or in a Go test setup?

**Comment by cdrexle** [comment]
Thanks for merging this in! Any idea when a new tag will be cut?

This is being tested in a go test setup, that writes an ocf file and immediately reads it out, using the same struct  type for both read and write.

**Comment by nrwiersma** [comment]
More than likely early next week some time.
