### ISSUE TITLE
logicalType - keep property

### ISSUE THREAD

**Issue by jwtryg** [hamba/avro#435]
Currently when parsing an avro schema, the [schema.go file](https://github.com/hamba/avro/blob/main/schema.go) contains a number of reserved properties that are removed from the schemas. These reserved properties include the `logicalType` property.

However, some projects, like apache iceberg, uses a number of logical types that are not included in the avro specification (see  [this](https://iceberg.apache.org/spec/#avro)) and therefore don't have corresponding `LogicalType`s defined. When parsing such an avro schema, these unknown logicalTypes are then simply ignored and furthermore removed from the schema propertiies which makes them impossible to detect.

My suggestion for a simple solution is that the logicalType properties are kept by removing it from the list of schemaReserved properties. Or do you have other alternatives?

**Comment by nrwiersma** [comment]
Someone floated an idea of supporting custom logical types. That could be an alternative.

**Comment by jwtryg** [comment]
That would be awesome! I guess that means a rather large change though, if the types that does not currently support logical types should also be able to support custom logical types.

However, I would be willing to take a stab at a PR for this, but I might need a bit of guidance :)

**Comment by nrwiersma** [comment]
Hey. You are welcome to have a go. Let me know where you get stuck and I will help if I can.

**Comment by jhump** [comment]
> My suggestion for a simple solution is that the logicalType properties are kept by removing it from the list of schemaReserved properties. Or do you have other alternatives?

FWIW, this wouldn't quite be enough. It would work to preserve the "map" logical type for arrays. But for the "timestamp-nanos" and "uuid" logical types for long and fixed[16] respectively, these get discarded at a different stage and are never in the property map to begin with.

**Comment by jhump** [comment]
Actually, it looks like "uuid" logical type for fixed[16] **is** in the spec, but it's not yet implemented by this module:
https://avro.apache.org/docs/1.12.0/specification/#uuid

**Comment by nrwiersma** [comment]
UUID is supported by this module, via `encoding.TextUnmarshaler` interface. There are too many packages for this to support a single one, but almost all of them support this interface.

**Comment by jhump** [comment]
@nrwiersma, "UUID" is currently only supported in this repo for **string** types. But the [spec](https://avro.apache.org/docs/1.12.0/specification/#uuid) also states that it can be used with fixed[16].
