### ISSUE TITLE
Bug - Integer overflow const defined

### ISSUE THREAD

**Issue by MovieStoreGuy** [hamba/avro#439]
## Context

Within the project [open telemetry collector contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib),  one of the components depends on this package. 

When trying to build for `linux/arm64`, it fails to build due to the file [config_x64.go](https://github.com/hamba/avro/blob/main/config_x64.go#L7) defining an integer value that overflows a 32bit int.

## Recommendations

It looks like this value should be a `int64` or `uint64` type instead of a `int` to avoid the integer overflow.

**Comment by nrwiersma** [comment]
`int` on a 64 bit system is up to 64 bits. Your build fails on `arm` not `arm64`.

**Comment by nrwiersma** [comment]
Released v2.25.1 that solve your issue. I now do build checks to hopefully catch this in future.

**Comment by MovieStoreGuy** [comment]
Thank you so much @nrwiersma, greatly appreciate it :)
