### ISSUE TITLE
avrogen fails to generate go struct from avro record with enum field

### ISSUE THREAD

**Issue by GeorgyBocharov** [hamba/avro#442]
[enum_record.avsc](https://github.com/user-attachments/files/16909641/enum_record.avsc.json)

Hamba version: v2.25.0

I get error "`Error: avro: unknown type: enum`" during generation of go struct from enum_record.avsc (file attached).
The command I use is  `avrogen -pkg=codec  enum_record.avsc`

In source code I see that hamba supports enum avro type, but during code generation it fails

**Comment by nrwiersma** [comment]
You schema is wrong. That is not how fields work.

```
{
  "type": "record",
  "name": "EnumRecord",
  "fields": [
    {"name": "test", "type": {"type": "enum", "name": "enum", "symbols": ["foo", "bar"]}}
  ]
}
```

**Comment by GeorgyBocharov** [comment]
oh, you are right. thanks
