### ISSUE TITLE
Access schema custom props at the AVRO Gen template Level

### ISSUE THREAD

**Issue by redaLaanait** [hamba/avro#444]
I’m facing a case where I need to use a custom template to handle some of my schemas that contain custom props. These props should be translated into special Go tags at the generated Go types level.

Is it possible to pass schema (and fields) custom props as template parameters?

If this change is accepted, I can open a PR for it. However, another issue #441 related to this area of code might need to be addressed first.

Thanks

**Comment by nrwiersma** [comment]
Could you give an example of you are trying to do?

**Comment by redaLaanait** [comment]
Sure!

Example of a custom schema:

```json

{
  "name": "example.AccountCreated",
  "type": "record",
  "fields": [
    {
      "name": "Project",
      "type": "string",
      "default": ""
    },
    {
      "name": "ID",
      "type": "string",
      "default": ""
    },
    {
      "name": "SubjectToken",
      "type": "string",
      "default": "",
      "pii": "subjectID"
    },
    {
      "name": "Subject",
      "type": "string",
      "default": "",
      "pii": "data"
    },
    {
      "name": "Method",
      "type": "string",
      "default": "email"
    }
  ]
}
```

Wanted to generate the corresponding type:

```go
type AccountCreated struct {
	Project      string        `avro:"Project"`
	ID           string        `avro:"ID"`
	SubjectToken string        `avro:"SubjectToken" pii:"subjectID"`
	Subject      string        `avro:"Subject" pii:"data"`
	Method       string        `avro:"Method"`
}
```

I do check custom props for other stuff at the template level, but those are more project-specific.

**Comment by nrwiersma** [comment]
It seems plausible to pass the custom props in the case of fields, not sure about any other types. The template seems a good extension point for this. You would need to extend `fields` I think to keep track of them.

**Comment by redaLaanait** [comment]
> It seems plausible to pass the custom props in the case of fields, not sure about any other types

This can be done also in the case of records; `typeDef` can be extended similarly:

```go
unc (g *Generator) resolveRecordSchema(schema *avro.RecordSchema) string {
	fields := make([]field, len(schema.Fields()))
	for i, f := range schema.Fields() {
		typ := g.generate(f.Type())
		fields[i] = g.newField(g.nameCaser.ToPascal(f.Name()), typ, f.Doc(), f.Name())
		// extend gen field type
		fields[i].Props = maps.Clone(f.Props())
	}

	typeName := g.resolveTypeName(schema)
	if !g.hasTypeDef(typeName) {
		typeDef := newType(typeName, schema.Doc(), fields, schema.String())
		typeDef.Props = maps.Clone(schema.Props())
		// extend gen typedef type
		g.typedefs = append(g.typedefs, typeDef)
	}
	return typeName
}
```

But first, I need to expose schema custom Props via a getter.
