### ISSUE TITLE
Ordering of types in union of null / type affecting type resolution

### ISSUE THREAD

**Issue by sebnyberg** [hamba/avro#45]
A schema with a union of `[ "null", "string" ]` will happily Unmarshal to a `*string`, but a union of `[ "string", "null" ]` throws an error.

For example: 

```
type SimpleRecord struct {
	ID *string `avro:"id"`
}
schema, err := avro.Parse(`{
	"name": "Person",
	"namespace": "umbrella.corp",
	"type": "record",
	"fields": [
		{ "name": "id", "type": [ "string", "null" ] }
	]
}`)
if err != nil {
	log.Fatal(err)
}
id := "abc"
in := SimpleRecord{ID: &id}
_, err = avro.Marshal(schema, in)
if err != nil {
	log.Fatal(err)
}
```

will fail with an error of `ID: avro: unable to resolve type *string`

Whereas changing the schema to 

```	
schema, err := avro.Parse(`{
	"name": "Person",
	"namespace": "umbrella.corp",
	"type": "record",
	"fields": [
		{ "name": "id", "type": [ "string", "null" ] }
	]
}`)
```

Will work without error.

**Comment by nrwiersma** [comment]
This is by design. From the avro spec:
> Note that when a default value is specified for a record field whose type is a union, the type of the default value must match the first element of the union. Thus, for unions containing "null", the "null" is usually listed first, since the default value of such unions is typically null.

So the default for a `*string` would be `null` so it must be first.

**Comment by sebnyberg** [comment]
Alright, that makes sense. The schema is automatically generated by Azure Data Factory so I'll go there and ask. Thanks!

**Comment by sebnyberg** [comment]
Necroing this issue to ask another question: 

> In Go structs, the following types are accepted: map[string]interface{}, *T, and a struct implementing **avro.UnionType**. When en/decoding to an interface{}, a map[string]interface{} will always be used.

I can't seem to find the interface called `avro.UnionType` in the codebase?

**Comment by nrwiersma** [comment]
Sorry, old docs that were left in, it was removed and replaced with a better mechanism using the resolver and interfaces. I will update the docs there.

**Comment by nrwiersma** [comment]
The docs have been fixed. Thanks for pointing out the mistake.

**Comment by sebnyberg** [comment]
Thank you for the rapid response, this gave me confidence in using this package.

**Comment by nrwiersma** [comment]
No problem, glad to help where I can.

**Comment by mentalisttraceur** [comment]
After running into this about a month or two ago and I was initially in agreement on this design decision, but after thinking about this for a while, I think this is a mistake.

[That part of the Avro spec](https://avro.apache.org/docs/current/spec.html#Unions) is only talking about when there is a default *at the Avro level* - that is, the schema explicitly contains a `default` field for that field, and the actual Avro-encoded message omits the value entirely. In other words, it is talking about fields like this:

{ "name": "foo", "type": [ "null", "string" ], "default": null }
{ "name": "foo", "type": [ "string", "null" ], "default": "" }

and saying that fields like this are invalid:

{ "name": "foo", "type": [ "null", "string" ], "default": "" }
{ "name": "foo", "type": [ "string", "null" ], "default": null }

But the spec is **not** saying anything about fields like this:

{ "name": "foo", "type": [ "null", "string" ] }
{ "name": "foo", "type": [ "string", "null" ] }

So

1. we should reject schemas like those middle two,
2. if we get one of those last two field definitions we should *never assume a default* but instead error out if there is no value included in the message, but also
3. we should resolve that last one into a `*string`.

That last one is both spec-conformant and *useful* - in a system where Avro is being used correctly, `{ "name": "foo", "type": [ "string", "null" ] }` is a valid field which will never have a default null value but *can* have a non-default null value.

And while Go does not distinguish between a zero-initialized-by-default pointer an explicitly-set-to-nil pointer, a pointer is still the most idiomatic and most programmer-friendly way to express the semantics of "this could be null (but must be explicitly set as such in the encoded message bytes)".

**Comment by mentalisttraceur** [comment]
See also Ryan Blue's comment on [AVRO-1803](https://issues.apache.org/jira/browse/AVRO-1803):

> I think the wording is somewhat confusing [...] it means that users commonly add a null default by explicitly adding it. If you don't add a default, the readers expect a value to be present.
>
> The default is only used when there is no value in the encoded bytes, but the reader expects one. The reader either gets the default that was set in the read schema, or will get an exception that there is no default value and the data file was missing the value.

This seems to strongly suggest to me, along with other experience about what scope standards tend to and ought to cover or not cover, that the intent of that part of the spec is **not** to say that nullable unions are in general only valid if null occurs first, but to require that *if a default value is specified in the schema*, it must match the first type (and then it uses the common example case of a nullable union *that is also null-by-default in the schema* to illustrate the point).

**Comment by nrwiersma** [comment]
I am gonna think about this and get back to you. Thanks for the input.

**Comment by mentalisttraceur** [comment]
Cheers, I appreciate it. Happy to help.

As an additional datapoint: I have to work with a system in production where I don't get to control the schemas that other teams use, and at least one of the teams has every one of their fields defined with null as the second type and no default.

So for working with their data, I've had to make a bunch of fields into `interface{}` at the Go level. This added boilerplate to do type assertions, and also I had to write a second struct with the same fields with their actual types in order to contain the boilerplate and loss of type-safety to just one spot in the code.

In our case I would have had to do a lot of that boilerplate anyway, because a lot of the code was already written to expect values instead of possibly nil pointers to values, but I think you can see the readability difference this can make in the general case.

**Comment by nrwiersma** [comment]
Yes, totally. You are correct that it was a design decision at the point that I wrote it, and I see your point. My initial thought at the time is that `*string` has a default of nil, and `[string, null]` has a default of `""`. 

What I now need to check is if making the change will break any fundamental concepts in the lib, or add massive amounts of complexity. We might also want to make this idea opt-in with settings.

**Comment by nrwiersma** [comment]
So I have had a look, and I think there is a lot of confusion around this topic.

> That part of the Avro spec is only talking about when there is a default at the Avro level - that is, the schema explicitly contains a default field for that field, and the actual Avro-encoded message omits the value entirely. In other words, it is talking about fields like this:

What you are saying here is a little incorrect. The default when reading is only applicable when using resolved schemas, which we dont support (eg. the writer schema has the field but the reader does) as the reader and writer schemas must be the same in our case. So i believe the case you are talking about is not applicable here. It is important to note that we have no real way of knowing what fields exist in data, just what the schema tells us.

For us the default is only used in the encoding, to write a field that was not given. But it is important to note that a value is always written for each field, even if that value is default. It is just that `null` has no writable bytes, but it is indicated in the union bytes which type we are reading.

This however does not invalidate the concept of allowing `[string, null]` as a `*string`. It is possible, but we add complexity to `decoderOfPtrUnion` in figuring out what is the non-nil schema type. so we can decode correctly. This however is not undoable, and would likely have only small localised changes.

After all of that, I am interested in your thoughts?

**Comment by nrwiersma** [comment]
@mentalisttraceur I gave it a shot, and it turns out to no be invasive at all, and the added complexity is almost none, and I think you are correct that there is no particular reason not to support this. 

Please give it a try and let me know what you think?

**Comment by sebnyberg** [comment]
For what it's worth, I have hundreds of these fields (and it's out of my control) so I'm very happy about this change.

**Comment by nrwiersma** [comment]
This has been fixed in [v1.1.0](https://github.com/hamba/avro/releases/tag/v1.1.0). Please let me know if you find any issues with it.

**Comment by mentalisttraceur** [comment]
Thanks! I have been too busy with other things for now to give any in-depth reply, but I agree with your reasoning about interpreting the spec, appreciate that you implemented this change, I'll let you know if I run into issues.

**Comment by mentalisttraceur** [comment]
Okay I had some time to test this. It seems to have broken something. Schemas that were parsing fine before now cause an error. Here's an example test to demonstrate:

```go
package foo

import (
	"testing"

	"github.com/hamba/avro"
)

const schema = `{"type":"record","name":"foo","fields":[{"name":"bar","type":["string","null"]}]}`

func failIfError(t *testing.T, err error) {
	if err != nil {
		t.Fatal(err)
	}
}

func TestFoo(t *testing.T) {
	_, err := avro.Parse(schema)
	failIfError(t, err)
}
```

Passes with v1.0.0, fails with v1.1.0.

**Comment by nrwiersma** [comment]
@mentalisttraceur Please open a separate bug for this one.

**Comment by nrwiersma** [comment]
@mentalisttraceur Fixed in #52

**Comment by mentalisttraceur** [comment]
@nrwiersma Yeah I just wasn't sure if it was due to the code change for this issue (I haven't had time to really grok how this code works enough to rule that out), will make a new issue n- oh wait you already fixed it.

Just tested, confirmed working. Nice! Thank you. You've got impressive turn-around times.

Is there going to be a v1.1.1 tag soon with this?

**Comment by nrwiersma** [comment]
@mentalisttraceur Thanks. 

Just tagged [v1.1.1](https://github.com/hamba/avro/releases/tag/v1.1.1) now.
