### ISSUE TITLE
Bug with `*big.Rat` since release v2.24.0

### ISSUE THREAD

**Issue by oderwat** [hamba/avro#453]
We use hamba/avro quite a lot and run into trouble because `*bit.Rat` is not working anymore since release v2.24.0.

The following code will decode to`0.000` when compiled with any release since v2.24.0.

```
package main

import (
	"fmt"
	"log"
	"math/big"

	"github.com/hamba/avro/v2"
)

const schemaString = `{
  "type": "record",
  "name": "PriceV1",
  "fields": [
    {
      "name": "Price",
        "type": [
          "null",
          {
            "logicalType": "decimal",
            "precision": 17,
            "scale": 4,
            "type": "bytes"
          }
        ]
      }
  ]
}`

type PriceV1 struct {
	Price *big.Rat
}

func main() {
	v := big.NewRat(1, 3)
	p := PriceV1{
		Price: v,
	}

	schema, err := avro.Parse(schemaString)
	if err != nil {
		log.Fatal(err)
	}

	e, err := avro.Marshal(schema, &p)
	if err != nil {
		log.Fatal(err)
	}

	o := PriceV1{}

	err = avro.Unmarshal(schema, e, &o)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("in: %s\n", p.Price.FloatString(4))
	fmt.Printf("out: %s\n", o.Price.FloatString(4))
}
```

Result for packages before v2.24.0:

```
in: 0.3333
out: 0.3333
```

Result starting with v2.24.0:

```
in: 0.3333
out: 0.0000
```

**Comment by nrwiersma** [comment]
Your schema is a nullable union, which is dereferencing the type, so you are actually decoding into a `big.Rat`. There was a bug that allowed this before `v2.24.0` that was patched out that would allow decoding into `big.Rat`.

**Comment by oderwat** [comment]
But I want to have a nullable union. We have`*big.Rat` with null as value.

**Comment by nrwiersma** [comment]
Use a `**big.Rat`. As noted in the Readme, `decimal` translates to `*big.Rat` and nullable union is `*T`, so `**big.Rat`.

**Comment by oderwat** [comment]
OK. Got it. Thank you!
