### ISSUE TITLE
Consider field aliases when marshaling to avro

### ISSUE THREAD

**Issue by mihaitodor** [hamba/avro#479]
I noticed this library supports [aliases](https://avro.apache.org/docs/1.12.0/specification/#aliases) for fields, but it only uses them when unmarshalling data. I'm not sure how to interpret the "An implementation may optionally use aliases to map a writer’s schema to the reader’s" sentence from the spec, but I was wondering if it might make sense to also evaluate them as field name candidates when marshalling data. Consider the following code:

```go
package main

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/hamba/avro/v2"
)

func main() {
	schema, err := avro.Parse(`
{
  "type": "record",
  "name": "foobar",
  "fields": [{
    "name": "foo",
    "aliases": [ "bar" ],
    "type": "string"
  }]
}
`)
	if err != nil {
		log.Fatal(err)
	}

	dummyInput := `{"foo": "gopher"}`
	// dummyInput := `{"bar": "gopher"}`
	var data any
	json.Unmarshal([]byte(dummyInput), &data)
	avroData, err := avro.Marshal(schema, data)
	if err != nil {
		log.Fatal(err)
	}

	var decoded struct {
		Bar string `avro:"bar"`
	}
	err = avro.Unmarshal(schema, avroData, &decoded)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%+v\n", decoded)
}
```

It prints `{Bar:gopher}` because field `foo` has `bar` as alias in the schema.

However, if you set `dummyInput` to `{"bar": "gopher"}`, then it will error out with `avro: missing required field foo`.

**Comment by nrwiersma** [comment]
> An implementation may optionally use aliases to map a writer’s schema to the reader’s.

This is talking about schema evolution, in terming of hamba/avro `SchemaCompatibility.Resolve`. It largely does not make sense IMO to use aliases for encoding, as aliases are about renaming fields, and having renamed a field while writing is weird.

**Comment by mihaitodor** [comment]
I see, thank you for the quick reply! I’m still exploring the AVRO space, trying to figure out what’s possible and what isn’t. Really appreciate all the hard work that went into this library!
