### ISSUE TITLE
Enum in map[string]interface{} does not encode

### ISSUE THREAD

**Issue by mcgrawia** [hamba/avro#55]
Hi, thanks for making this great library. My team and I have a use case where we are using Go to encode many kinds of messages for writing to kafka. As a result, we are using the map[string]interface{} encoding method. Maybe I am not configuring something correctly but it seems like nullable enums do not work in this scenario. Please let me know if there is something I need to fix. Here is a reproducible example:

```go
package main

import (
	"fmt"
	"github.com/hamba/avro"
)

func main() {
	schema, err := avro.Parse(`
{
	"type": "record",
	"name": "test", 
	"fields": [
		{"name": "PET", "type": ["null", {"type": "enum", "name": "pet", "symbols": ["dog", "cat"]}]}
	]
}`)
	if err != nil {
		fmt.Print(err)
		return
	}

	inf := map[string]interface{}{
		"PET": "dog",
	}

	_, err = avro.Marshal(schema, inf)
	if err != nil {
		fmt.Printf("could not encode: %v\n", err)
	}
}
```

This returns the error:
```
could not encode: avro: unknown union type string
```

Stepping through a debugger, it looks like it's trying to find an encoder for "string" but "enum" and "pet" are found. I think this was in this function: https://github.com/hamba/avro/blob/master/schema.go#L96

Thanks for the help

**Comment by nrwiersma** [comment]
Hi,

in the `map[string]interface{}` record case, the union must be a `map[string]interface{}` with the key as the named type. So the following works:
```go
package main

import (
	"fmt"

	"github.com/hamba/avro"
)

func main() {
	schema, err := avro.Parse(`
{
	"type": "record",
	"name": "test", 
	"fields": [
		{"name": "PET", "type": ["null", {"type": "enum", "name": "pet", "symbols": ["dog", "cat"]}]}
	]
}`)
	if err != nil {
		fmt.Print(err)
		return
	}

	inf := map[string]interface{}{
		"PET": map[string]interface{}{
			"pet": "dog",
		},
	}

	_, err = avro.Marshal(schema, inf)
	if err != nil {
		fmt.Printf("could not encode: %v\n", err)
	}
}

```

I will point out that using maps if a fair bit slower than using structs in the decode case, and more painful in the encode case. I obviously dont understand your use case, but in most cases, structs are the way forward.

Also for kafka I would suggest using a schema registry, the `avro/registry` client and encoding the schema id into the message (there is a specific format for that). This makes evolving schemas trivial in the future. This use case is the reason I wrote the library to start with.

**Comment by mcgrawia** [comment]
thanks @nrwiersma! that did the trick. Also thank you for pointing me to the `avro/registry` client. I was about to implement my own and that will save me a lot of time. 

Does this library have functions for serializing the schema id with the avro body? I couldn't find any methods to do that. If there isn't, do you know of any docs that are helpful to understand the binary format?

Thanks

**Comment by nrwiersma** [comment]
No worries.

The lib does not handle this step for you, as it is done in different way depending on the use case. The info you need can be found here: https://docs.confluent.io/current/schema-registry/serdes-develop/index.html#wire-format. Really simple to implement.

**Comment by mcgrawia** [comment]
Awesome, thank you @nrwiersma! If anyone else sees this thread, I was able to implement it with:

```go
buffer := &bytes.Buffer{}
_, err = buffer.Write([]byte{0})
if err != nil {...}

// write id in big-endian
err = binary.Write(buffer, binary.BigEndian, uint32(ID))
if err != nil {...}

// encode data
enc := avro.NewEncoderForSchema(schema, buffer)
err = enc.Encode(data)
if err != nil {...}
```
