### ISSUE TITLE
Implicit type coercion features

### ISSUE THREAD

**Issue by mcgrawia** [hamba/avro#59]
Hi @nrwiersma,

Does this library support the ability to convert numerical types implicitly? The LinkedIn go avro library seems to support this: https://github.com/linkedin/goavro#translating-from-go-to-avro-data

> When translating from native Go to either binary or textual Avro data, goavro generally requires the same native Go data types as the decoder would provide, with some exceptions for programmer convenience. Goavro will accept any numerical data type provided there is no precision lost when encoding the value. For instance, providing float64(3.0) to an encoder expecting an Avro int would succeed, while sending float64(3.5) to the same encoder would return an error.

If not, would it be difficult to add features like this? As you know, our use case involves serializing arbitrary customer data. Some customers send us parquet files with 32 bit types and we would like to automatically serialize those into 64 bit Avro types. That way the customers don't have to care whether their files are 32 or 64, we can handle both.

Thanks for the help!

**Comment by nrwiersma** [comment]
Hi @mcgrawia,

We do not allow for this. The reasoning is as follows: 

`goavro` does its schema validation and encoding in a single pass, meaning the have access to the type and value at the same time. While a valid approach, it is very very slow as you validate the schema multiple times. 

`hamba/avro` uses a different approach with the goals of speed and reliability. We deal with the type first and make an encoding/decoding plan then run the plan on the data. The plan is created exactly once per type (assuming struct encoding). 

So with your suggestion we have no idea if the float type is safe to be an int/long as we do not have access to the data. This would cause a plan to be created that possibly/likely would fail to encode, randomly returning errors. This seems like a fairly bad thing to do, as in production I would not like a library that is unreliable at encoding data.

There is however one exception to all this, which is encoding `map[string]interface{}` records. With this type, we have to work out the schema-encoder on the fly as we literally have not idea what we are getting. The issue in this case is that making the change you request would bleed into the struct encoding case, and I have not way to know what came before to narrow the choice.

If this is something that still interests you, I do have one idea, which is to add a config option to allow precision loss during encoding. Turning this on could perhaps allow `float32 -> int` and `float64 -> long` encoding (or some small set of choices). I dont know if this would satisfy your case or not?

**Comment by mcgrawia** [comment]
Thanks for the detailed explanation. That makes sense. I should clarify our use case more closely as the `goavro` library's features are more than we need. 

For our use case, we only need the ability for Avro doubles and longs to accept their 32 bit counterpart Go types. For example, we would like to be able to provide a Go `float32` for an Avro schema that is expecting a `double` and similarly for a Go `int32` and an Avro `long`. We do not need the ability to mix between ints and floats, so there should never be a loss of precision. It seems like this should be doable while creating the plan you describe above? If you know the struct type is a 32 bit version and the Avro is a 64, the plan should be able to convert with the struct type information alone?

**Comment by nrwiersma** [comment]
Yes, that is very doable, and still safe and reliable. It should be fairly simple to implement as well.

**Comment by mcgrawia** [comment]
Awesome! I am happy to take a stab at a PR for this. Do you have any suggestions where it would make sense to implement it?

**Comment by nrwiersma** [comment]
That would be great. It should be implemented in `codec_native.go`. Look the the function `createEncoderOfNative` and you will pick up how this is handled, and 2 new codecs will be needed. Hope you like playing with unsafe 😄 .

**Comment by mcgrawia** [comment]
Thanks @nrwiersma, I just opened a PR. Let me know what you think when you have time
