### ISSUE TITLE
Custom types

### ISSUE THREAD

**Issue by fantyz** [hamba/avro#67]
Hi,

I'm reading some json data that contains a string with a timestamp that needs a custom `UnmarshalJSON` to unmarshal properly. I've crated a `type Timestamp time.Time` with an `UnmarshalJSON` method that works. Next I need to serialize this data to avro.

Naively just trying to use `avro.Marshal` on it unsurprisingly returns an `avro: mypkg.Timestamp is unsupported for Avro string` error.

Is there an easy way to get Avro to treat my custom `Timestamp` type as a string for a avro string field?

I can't seem to find anything similar to how `encoding/json` works where I just need to implement my own `MarshalJSON` function.

I'd like to avoid having to create the same struct again, just with string types for the timestamps, and copy over all the values to get it to serialize to Avro - its a fairly big struct.

**Comment by nrwiersma** [comment]
Hi,

This is an interesting thought. It is perhaps possible that we could support `TextMarshaler` for string as a fallback. As time.Time supports this already, it should work out the box. 

I will look into this.

**Comment by nrwiersma** [comment]
So it turns out implementing `TextMarshaler` is fairly complex. The number of cases that needs to be dealt with are fairly large. I would like to avoid this complexity if possible.

The options at this point are to allow for `Stringer` interface, but this does not deal with decode.

I can also suggest perhaps adding a second `time.Time` field with the tags `json:"-" avro:"your_field_name"`. To encode `time.Time` use a logical type which will be more efficient than

**Comment by fantyz** [comment]
Why wouldn't an interface similar to `Stringer` work for decoding?

It would decode the value using the schema type - and if the fields type is different from what's expected, it would use an interface that allow you to pass a value of the type that the schema dictate and leave it up to the user to do the rest (eg. just like it would call `String()` to get a string representation which match the schema that can then be encoded subsequently when trying to encode).

You would probably need a pair of interfaces for each different type though, which is slightly annoying, but I don't see why it wouldn't work?

I'm kinda in a hurry, so I'll work around this for now - but I think its a worth while thing to add 😄

**Comment by nrwiersma** [comment]
> t would decode the value using the schema type - and if the fields type is different from what's expected, it would use an interface that allow you to pass a value of the type that the schema dictate and leave it up to the user to do the rest (eg. just like it would call String() to get a string representation which match the schema that can then be encoded subsequently when trying to encode).

What you are describing here is TextMarshaler and TextUnmarshaler.

The issue with TextMarshaler specifically is that it can be implemented by a pointer or non-pointer struct, so both need to be checked for the implementation to be detected. This actually is handled by 2 separate parts of encoding. I need to find a way/place that can handle the detection. Further when given an interface, the underlying struct/alias can possibly implement the interfaces as well. As you dig in, so the number of cases for implementing the interfaces grow. My concern is that it will be a sprawling nightmare to handle every single case.

I will have to look at the situation more closely when I have a moment to determine if there is a way to handle this more elegantly.

**Comment by fantyz** [comment]
It sounds like you would do it through reflection? Can't you instead let Go do this for you by doing a simple type assertion instead? That would take the complexity of how the user has chosen to implement it out of the equation - and it would be an almost one-liner you could do where needed easily.
```
package main

import (
	"fmt"
	"encoding"
)

type SomeType string

func (s SomeType) MarshalText() ([]byte, error) {
	return []byte(string(s)), nil
}

func main() {
	var i interface{} = SomeType("hello")
	s := i.(encoding.TextMarshaler)
	out, _ := s.MarshalText()
	fmt.Println(out)
}
```

**Comment by nrwiersma** [comment]
This is unfortunately not how this library works. It isnt even based on reflection but a "cheap" version of it based around unsafe pointers. It is how I managed to make it fast. The general concept is to make reusable en/decoders that are cacheable, so I do not know the type and value at the same point in time. This is where the complexity sneaks in.

I do have an idea to handle it further up the decision tree, but will need to take some time to validate it against all the expected cases.

**Comment by nrwiersma** [comment]
So I managed to put something together that seems to work/passes tests. If you have a moment, would be awesome to test it in a real use case.

**Comment by fantyz** [comment]
My usecase has changed sadly, so I don't have a real test case I can easily throw together any more.

But I think its a great addition 👍

It would probably make sense to add marshalers for the other data types as well and not just strings? It makes life a lot easier for me as user when I can let this package handle (all of) the serialization/deserialization to and from a struct that actually has the types I need. Another one that would have been convenient for me at the point of opening this issue in the first place would be a `time.Time` that is serialized to and from an int in Avro (unix timestamp).

**Comment by nrwiersma** [comment]
`time.Time` can already be serialised like this, using logical types (see [here](https://github.com/hamba/avro#types-conversions) under `long.timestamp-millis` and `long.timestamp-micros`. Further Avro has very strict typing and formatting, so it does not make sense to allow just any type to serialise to any type. In my opinion that would make things far more complex for the user, as should you get the type wrong based on the schema you will break the encoding.

**Comment by fantyz** [comment]
You assume I can change the Avro schema for that to work.

There are **a lot** of use cases where you simply need to consume existing data and have no influence on what the schema looks like.

The problem boils down the the same- I have data in a fixed Avro schema that I need to de-serialize to a datatype in Go that is fit for purpose (like an `int` that needs to become a `time.Time`) and I would love to avoid having to de-serialize the data twice if I can avoid it; first to a type that fits the schema and then to the type I actually need to work with.

I'm not suggesting I should be messing with the encoding part of Avro at all - rather that if you have an avro schema that specifies a given field to be of some type (eg. `int`) but the Go field it is intended to de-seraialize to isn't an `int`, then the library would use a `IntUnmarshaler` (or whatever name you like better) implemented by the type to populate it.

The same goes the other way. The schema expects a given field to be of a certain type. If it is not, then it calls `<type>Unmarshaler` that the type must implement to get it from its type to the expected type. From here the library would do the actual encoding of the expected type to Avro. That doesn't leave any room for the user to be breaking the encoding. It just makes it possible to avoid having do double encode/decode things.

**Comment by nrwiersma** [comment]
I understand the idea, it is just massively complex. Even if it was constrained to "native" types we are talking about 10 different marshaler interfaces with their counterpart unmarshalers. This would then likely leak into enums fixed types and arrays and the list just grows. The be honest, I really dont see this as a feasible option.

The only use case I foresee is to add a `MarshalAvro` and `UnmarshalAvro`, where you are given the schema and reader/writer and leave you on your way. Use this would obviously be unadvisable as if you read the wrong type you would have broken the rest of the decode, and if you write the wrong type, you will never be able to decode it again. But it is an option non the less.

**Comment by TuSKan** [comment]
I have the same problem. Load data from CSV files, from different formats of timestamp.
Define as:  *type Timestamp time.Time*
Timestamp is reflect ConvertibleTo  time.Time
What do you think to allow convertible types to logical types?

**Comment by TuSKan** [comment]
Seems to work fine
https://goplay.tools/snippet/Dq5DLJ6LhcS

**Comment by nrwiersma** [comment]
You have missunderstood. `ptr` is an `unsafe.Pointer` to the type. Where you are casting, where Go knows the 2 types, `avro` does not have this info.

**Comment by TuSKan** [comment]
I have just updated to use the unsafe.Pointer. Please let me know if is correct

**Comment by nrwiersma** [comment]
You need to send a new link.

**Comment by TuSKan** [comment]
https://goplay.tools/snippet/9OVeBlCbWZF

**Comment by nrwiersma** [comment]
Looks good in principle. Would gladly accept a PR to implement this.

**Comment by TuSKan** [comment]
Great!!! :) Would be a pleasure
Just give me some tips to start.
I was thinking on *codec_native.go*  on function *createEncoderOfNative* on case *reflect.Struct*  change comparation *typ.RType()==timeRType* to *typ.AssignableTo(timeRType)*
What do you think?

**Comment by nrwiersma** [comment]
`typ.AssignableTo` does not exist. You could perhaps move both to `Type1` and check `AssignableTo` on that. The location looks about right.

**Comment by TuSKan** [comment]
I couldn't be able to run *golangci-lint* on my notebook.
I just wrote a draft of the README.
Any suggestions are welcome.

**Comment by nrwiersma** [comment]
If you cannot install it locally, although this should work on all OSes, you can run golangci-lint in docker, as they provide a docker container.

**Comment by nrwiersma** [comment]
Please feel free to contribute where things are lacking. I would not be able to do this without the communities support.
