### ISSUE TITLE
Encoding/Decocing time.Time zero value does not result in same value

### ISSUE THREAD

**Issue by mscno** [hamba/avro#69]
Hi,

I am stuggling with encoding/decoding of zero value time.Time fields. If I encode a struct with zero value time, and decode it again, the value is no longer zero but instead `1754-08-30 22:43:41.128654848`.

Here is a sample code to reproduce:

```go
package main

import (
	"github.com/davecgh/go-spew/spew"
	"github.com/hamba/avro"
	"github.com/rs/zerolog/log"
	"time"
)

type TimeStruct struct {
	Timestamp time.Time `avro:"timestamp"`
}

func main() {
	const SchemaString = `{
    "type": "record",
    "name": "timestruct",
    "namespace": "test",
    "fields": [
		{"name": "timestamp", "type":{"type":"long","logicalType":"timestamp-micros"}}
    ]
}`
	schema, err := avro.Parse(SchemaString)
	if err != nil {
		log.Fatal().Msg(err.Error())
	}

	ts := TimeStruct{Timestamp: time.Time{}}

	bytes, err := avro.Marshal(schema, ts)
	if err != nil {
		log.Fatal().Msg(err.Error())
	}

	var ts2 TimeStruct

	err = avro.Unmarshal(schema, bytes, &ts2)
	if err != nil {
		log.Fatal().Msg(err.Error())
	}

	if ts.Timestamp != ts2.Timestamp {
		log.Fatal().Msgf("ts != ts2: %v != %v",ts,ts2)
	}

}

```

I found this on UnixNano function from time package:

*UnixNano returns t as a Unix time, the number of nanoseconds elapsed since January 1, 1970 UTC. The result is undefined if the Unix time in nanoseconds cannot be represented by an int64 (a date before the year 1678 or after 2262). Note that this means the result of calling UnixNano on the zero Time is undefined. The result does not depend on the location associated with t.*

Is this the expected behavior of encoding/decoding zero value or is it a bug?

**Comment by nrwiersma** [comment]
Hi,

I think it is a bug. It is possible I am overflowing an int64. I will look deeper into this.

**Comment by nrwiersma** [comment]
I have a fix that seems to work. Can you perhaps confirm?

**Comment by mscno** [comment]
Hi, just pulled the fix commit, and I can confirm that it now works as expected and encode/decode of zero value time.Time yields the same result.

Thanks for the quick fix!

**Comment by nrwiersma** [comment]
Thanks for confirming. Appreciate the effort. I will version this in later this week.
