### ISSUE TITLE
Example of reading an OCF file

### ISSUE THREAD

**Issue by alexflint** [hamba/avro#7]
Can you provide an example of using this library to read an OCF file?

**Comment by nrwiersma** [comment]
Hi,

You can find what you are looking for here: https://godoc.org/github.com/hamba/avro/container, with an example. I still need to implement the codec support though, but it should be relatively quick work if you need it.

**Comment by nrwiersma** [comment]
Hi,

I have finished up the codecs in `v1.0.0` and renamed the `container` package to `ocf`. You can now find the docs in https://godoc.org/github.com/hamba/avro/ocf. 

Let me know if it works for you.

**Comment by alexflint** [comment]
Wow, amazing, thank you @nrwiersma !
