### ISSUE TITLE
Invalid name when name contains periods '.'

### ISSUE THREAD

**Issue by raiRaiyan** [hamba/avro#72]
When parsing a schema with a name containing period (e.g "abcd_1.0_efg") I get invalid name error. The issue seems to be the parser splits the name by '.' and invalidates any substring starting with a number (0_efg is invalid in this case)

From [here](https://stackoverflow.com/a/52340734/5189158), I understand periods in name is invalid. But I would like to disable name verification and the library does not seem to have that option. 

Is there any plan to bring in the option to disable name verification. If not, is there any hack I can use to disable name validation?

**Comment by nrwiersma** [comment]
Periods in names is disallowed by the [Avro Spec](https://avro.apache.org/docs/current/spec.html#names). There is no way to get around this in the library and currently no plans to allow this.

It would be possible to allow this functionality, but only at a library level.

**Comment by nrwiersma** [comment]
Can I ask exactly what your situation is that this is needed? Do you not control the schema? Why is a `.` used in the schema?

**Comment by nrwiersma** [comment]
Closed due to inactivity. If you would like to discuss this further, please reopen the issue.
