### ISSUE TITLE
Compatible Schema Registry client

### ISSUE THREAD

**Issue by pedromss** [hamba/avro#77]
Hi, first of all congratz. This is the only library for Go I've found that is truly simple to use and hides the complexity of Go <-> Avro conversions from the user, unlike others such as the linkedin one.

I was wondering if you know of a schema registry client compatible with the interfaces provided here. I started out using 
- https://github.com/riferrei/srclient as the schema registry client
- https://github.com/linkedin/goavro as the schema parser and record encoder/decoder (implicit from `riferrei/srclient`

However `linkedin/goavro` still let's alot of details up to the user like dealing with the quirks of unions in Go struct types, so I (fortunately) found this one.

The `srclient/riferrei` already provides schema caching but in the form of `*srclient.Schema`. I think this lib would benefit from a complementary lib (possibly in another repo) to interact with the schema registry and provide in memory caching for the parsed Schemas.

At the moment I can do (pseudo-code):
```go
schema, err := srclient.FetchLatestSchema(topic) // srclient already provides caching, so won't make the network request if it already has the schema
return toHambaSchema(schema) // this however isn't cached and would constantly be parsing the schema
```

Is there such a client compatible with the interfaces exposed here? Would you see a benefit in such a client?

**Comment by nrwiersma** [comment]
Hi, thanks very much.

This library contains a schema registry client compatible with the `Confluent Schema Registry`.  You can find the documentation for it here: https://pkg.go.dev/github.com/hamba/avro@v1.5.1/registry. This does the schema parsing for you and handles caching when getting a schema by id.

**Comment by adrian-chang-alcover** [comment]
Hello
Thanks for this great library.

I am trying to comsume using confluent_kafka on Python a topic produced using this library. However I got this error.
"Unknown magic byte. This message was not produced with a Confluent Schema Registry serializer"

I am producing using this code
`b, err := avro.Marshal(c.schema, &rawActivityAvro)`

Do I have to do anything to make the message compatible with confluent_kafka on Python ?

**Comment by nrwiersma** [comment]
Hi,

Yes, you need to format the message as per the confluent [wire format](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#wire-format). This is outside the scope of this library.
