### ISSUE TITLE
Serializing a map results in a panic

### ISSUE THREAD

**Issue by DasTushar** [hamba/avro#82]
I'm converting the data to a map(using avro.Unmarshal), modify the fields I'm interested in, and then again use avro.Marshal() on the map.

In the above process avro.Marshal() panics at https://github.com/hamba/avro/blob/master/codec_record.go#L293

Here is a sample code to reproduce the panic:

```go
package main

import (
	"github.com/sirupsen/logrus"
	"github.com/hamba/avro"
)

func main() {
        schema, _ := avro.Parse(`{"namespace": "People","type": "record","doc": "People information","name": "People",
"fields": [{"name": "name","type": ["null",{"type": "string","avro.java.string": "String"}],"doc": "Name of the person.","default": null},
{"name": "address","type": ["null",{"type": "record","doc": "Address information","name": "Address","fields": [{"name": "name","type": ["null",{"type": "string","avro.java.string": "String"}],"doc": "An optional name of the recipient","default": null}],"doc": "","default": null}]}]}`)

	p := People{
		Name:    "TD",
		Address: &Address{Name: "DT"},
	}

	pBytes, err := avro.Marshal(schema, &p)
	if err != nil {
		logrus.New().Fatal(err)
	}

	resMap := make(map[string]interface{})

	err = avro.Unmarshal(schema, pBytes, &resMap)
	if err != nil {
		logrus.New().Fatal(err)
	}

	pBytes, err = avro.Marshal(schema, &resMap)
	if err != nil {
		logrus.New().Fatal(err)
	}

}

type People struct {
	Name    string   `avro:"name"`
	Address *Address `avro:"address"`
}

type Address struct {
	Name string `avro:"string"`
}
```

**Comment by nrwiersma** [comment]
So firstly, `People.Name` and `Address.Name` are nullable unions, so they should be `*string` not `string`. This should have caused an error, but didnt. This is now the case.

**Comment by xmlking** [comment]
we also have many `nullable unions` for string/int type fields. since my structs are generated from protobuf, i have limited control over declaring struct field as `*string` or `string`

**Comment by nrwiersma** [comment]
@xmlking For encode this may work, but for decode it will definitely not, and there is not much that can be done about that.

**Comment by xmlking** [comment]
agree, thanks for your quick support.
if this binary —> interface{} —> binary flow works, i will have no issues
