### ISSUE TITLE
ocf: append serialized avro

### ISSUE THREAD

**Issue by torfjor** [hamba/avro#84]
Hi!

Our usecase is as follows: We are streaming Avro messages from multiple Kafka topics produced on Confluent Cloud and want these imported to BigQuery for analytics. From what I gather from the BigQuery docs the Avro files must be in OCF format (schema included).

We already use `registry` from this project to look up the schema from the messages and it would be nice if we could use `ocf` to produce the container files. We would like to avoid having to convert the raw Avro bytes to `interface{}` before we append them to the OCF, though. Could this be a possible addition to the API surface of `ocf`?

**Comment by nrwiersma** [comment]
Hi,

This is an interesting use case. This does seem feasible, although you would be responsible from ensuring that the schema you write is the same as the schema in the OCF.

Would you like to take a crack at a PR?

**Comment by nrwiersma** [comment]
Could you try this to see if it works for your use case: https://github.com/hamba/avro/tree/raw-ocf

**Comment by nrwiersma** [comment]
Closing due to age. Feel free to reopen if you still need this feature.

**Comment by yusufozturk** [comment]
@nrwiersma I need to same thing but that branch is not exist anymore. Is this possible today?

Thanks.

**Comment by nrwiersma** [comment]
Yes, you can use the encoder `Write` method: https://pkg.go.dev/github.com/hamba/avro/v2@v2.1.0/ocf#Encoder.Write
