### ISSUE TITLE
Convert textual Avro data (Avro in JSON format) to native Go

### ISSUE THREAD

**Issue by xmlking** [hamba/avro#85]
is it possible Convert textual Avro data (Avro in JSON format) to native Go interface{} ?

Ref: https://github.com/linkedin/goavro
```go
    // Convert textual Avro data (Avro in JSON format) to native Go form
    native, _, err := codec.NativeFromTextual(textual)
    if err != nil {
        fmt.Println(err)
    }
```

I need to read multi line [jsonl](https://jsonlines.org/) file and scan each line,
1. convert Avro in JSON format string to generic (Go `interface{}`)
2. convert `generic` int `binary` with `avro.Marshal(schema, generic)`
3. publish `binary`  to a pubsub messaging system.

**Comment by nrwiersma** [comment]
This library does not support textual Avro at all.
