### ISSUE TITLE
Example for slices

### ISSUE THREAD

**Issue by derekperkins** [hamba/avro#92]
I'm having a difficult time understanding how to unmarshal into an array of a typed struct. The readme mentions that you have to register the types, but I don't see where that is happening in the tests. https://github.com/hamba/avro/blob/master/decoder_array_test.go#L39-L51

When I naively register my type, I get an error for `avro: decode union type: unknown union type`. I've copied the example from the readme below and turned some of it into slices. Can you help point me in the right direction? I think it would be very useful to add to the readme too.

```
type SimpleRecord struct {
	A int64  `avro:"a"`
	B string `avro:"b"`
}

schema, err := avro.Parse(`{
    "type": "record",
    "name": "simple",
    "namespace": "org.hamba.avro",
    "fields" : [
        {"name": "a", "type": "long"},
        {"name": "b", "type": "string"}
    ]
}`)
if err != nil {
	log.Fatal(err)
}

avro.Register("mytype:", SimpleRecord{})
avro.Register("mytype:", &SimpleRecord{})

in := []SimpleRecord{{A: 27, B: "foo"}}

data, err := avro.Marshal(schema, in)
if err != nil {
	log.Fatal(err)
}

fmt.Println(data)
// Outputs: [54 6 102 111 111]

out := []SimpleRecord{}
err = avro.Unmarshal(schema, data, &out)
if err != nil {
	log.Fatal(err)
}

fmt.Println(out)
// Outputs: {27 foo}
```

**Comment by nrwiersma** [comment]
You only need to register types with `Register` for a union type, so it knows what the type looks like.

It looks like the issue you are having is that schema does not contain an array. I suggest you read the [spec](http://avro.apache.org/docs/current/spec.html#schemas) to fully understand schemas.

This is the correct schema and code:

```
type SimpleRecord struct {
		A int64  `avro:"a"`
		B string `avro:"b"`
	}

	schema, err := avro.Parse(`{"type": "array", "items":
{
    "type": "record",
    "name": "simple",
    "namespace": "org.hamba.avro",
    "fields" : [
        {"name": "a", "type": "long"},
        {"name": "b", "type": "string"}
    ]
}}`)
	if err != nil {
		log.Fatal(err)
	}

	in := []SimpleRecord{{A: 27, B: "foo"}}

	data, err := avro.Marshal(schema, in)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(data)
	// Outputs: [1 10 54 6 102 111 111 0]

	out := []SimpleRecord{}
	err = avro.Unmarshal(schema, data, &out)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(out)
	// Outputs: [{27 foo}]
```

**Comment by yusufozturk** [comment]
I think this is worth to be added on documentation.. Probably many people will work with slices and they will have the same issue.
