### ISSUE TITLE
Trying to marshal []map[string]interface{}

### ISSUE THREAD

**Issue by BenHiramTaylor** [hamba/avro#97]
Firstly I apologize If this is obvious, this is my first real project in GO so I am learning as I go along!

I am trying to create a microservice to ingest raw JSON (of any format) and create Avro out of it, this is a previous job that exists in Python that I have to convert over, i am using structs to keep track of and dynamically map fields to the schema, however, I get an issue when marshalling the data, the Avro is in the format:
```go
type Field struct {
	Name      string   `json:"name"`
	FieldType []string `json:"type"`
}

type Schema struct {
	Type      string  `json:"type"`
	Name      string  `json:"name"`
	Namespace string  `json:"namespace"`
	Fields    []Field `json:"fields"`
}

type ParsableSchema struct {
	Type  string `json:"type"`
	Items Schema `json:"items"`
}
```
In order to parse unknown JSON I am using maps of string to interface (to represent a JSON object), I have added below the AVSC that I generated with some sample data, the JSON does match this schema, but when I try to marshal a slice of this JSON, I get the error: `[]map[string]interface {}: avro: unknown union type double`
I have tried wrapping the schema in a `{"type":"array", "items": the avsc here}` but I still get the same issue, again this is my first Go Project so apologies if i am missing something "obvious", this is a lot different than the Python i am used to :)

```
{
  "type": "record",
  "name": "TestTable",
  "namespace": "TestTable.avsc",
  "fields": [
    {
      "name": "TestData",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "NEWNEWROW",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "NewValue",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "ExampleNest_NestedKey",
      "type": [
        "int",
        "null"
      ]
    },
    {
      "name": "ExampleNest_DoubleNest_DOUBLENESTVAL",
      "type": [
        "boolean",
        "null"
      ]
    }
  ]
}
```

**Comment by BenHiramTaylor** [comment]
(you can ignore the [{](url) on the ParsableSchema struct, not sure where it came from but it isn't in my code)

**Comment by nrwiersma** [comment]
Hi.

I am guessing here, but I think the issue is with the `ExampleNest_NestedKey` field. When Go unmarshals JSON into `map[string]interface{}` all numbers are expressed as `float64`. This is obviously not a valid input for an `[int, null]` union.

I would check your map to confirm this.

**Comment by BenHiramTaylor** [comment]
Thank you for the quick reply! i have tweaked the code to incorporate floats, (i also tried converting all floats to ints), i have added floats as a mapping to the Avro schema if the value is detected as a float using the reflect module, the schema generated does get mapped as a float now like you said, however i still have the same error when trying to marshal.
I have also tried marshalling without the `"type":"array","items":the per record schema` but i get `[]map[string]interface {} is unsupported for Avro record` which i believe is intentional, as it is not in the format of array schema.
Below is the schema and the formatted records i am trying to parse incase that helps:
AVSC:
```
{
  "type": "array",
  "items": {
    "type": "record",
    "name": "TestTable",
    "namespace": "TestTable.avsc",
    "fields": [
      {
        "name": "TestData",
        "type": [
          "string",
          "null"
        ]
      },
      {
        "name": "NEWNEWROW",
        "type": [
          "boolean",
          "null"
        ]
      },
      {
        "name": "NewValue",
        "type": [
          "string",
          "null"
        ]
      },
      {
        "name": "ExampleNest_DoubleNest_DOUBLENESTVAL",
        "type": [
          "boolean",
          "null"
        ]
      },
      {
        "name": "ExampleNest_NestedKey",
        "type": [
          "float",
          "null"
        ]
      }
    ]
  }
}
```
JSON:
```json
[
  {
    "ExampleNest_DoubleNest_DOUBLENESTVAL": null,
    "ExampleNest_NestedKey": null,
    "NEWNEWROW": false,
    "NewValue": null,
    "TestData": "A"
  },
  {
    "ExampleNest_DoubleNest_DOUBLENESTVAL": true,
    "ExampleNest_NestedKey": 3,
    "NEWNEWROW": null,
    "NewValue": "a",
    "TestData": "A"
  },
  {
    "ExampleNest_DoubleNest_DOUBLENESTVAL": null,
    "ExampleNest_NestedKey": null,
    "NEWNEWROW": null,
    "NewValue": "four",
    "TestData": "NewRow"
  }
]
```

**Comment by nrwiersma** [comment]
Should the `[float, null]` not be `[double, null]`. `float` in avro is `float32` and `double` is `float64`?

**Comment by BenHiramTaylor** [comment]
That was it! lack of avro knowledge let me down, i have corrected the field mapping and it dumps fine!, thank you for your help
