### ISSUE TITLE
avro: unknown type: long.timestamp-micros

### ISSUE THREAD

**Issue by BenHiramTaylor** [hamba/avro#98]
Sorry for another issue, I am using an encoder to Encode map[string]interface, but the schema seems unable to parse long.timestamp-micros, I have included my schema below, including the map i am trying to parse when this fails. I can also confirm that the TimestampTest is a time.Time object as mentioned in your mappings.
Schema: 
```
{
  type: "record",
  name: "TestTable",
  namespace: "TestTable.avsc",
  fields: [
    {
      name: "ExampleNest_DoubleNest_DOUBLENESTVAL",
      type: [
        "boolean",
        "null"
      ]
    },
    {
      name: "ExampleNest_NestedKey",
      type: [
        "int",
        "null"
      ]
    },
    {
      name: "TestData",
      type: [
        "string",
        "null"
      ]
    },
    {
      name: "NewValue",
      type: [
        "string",
        "null"
      ]
    },
    {
      name: "TimestampTest",
      type: [
        "long.timestamp-micros",
        "null"
      ]
    }
  ]
}
```

Record:
```
map[ExampleNest_DoubleNest_DOUBLENESTVAL:true, ExampleNest_NestedKey:<nil>, NewValue:<nil>, TestData:A, TimestampTest:2021-01-02 15:04:05 +0000 UTC]
```

**Comment by nrwiersma** [comment]
Hi,

`long.timestamp-micros` is not a valid type in avro, you are looking for `{"type": "long", "logicalType": "timestamp-micros"}` to create a logical type.

**Comment by nrwiersma** [comment]
just as a note, for a nullable union it is more common to have `["null", "string"]` then the other way round as in a field, only the first value in union can be the default.

**Comment by BenHiramTaylor** [comment]
Ah makes sense! got it working now thank you! and good to note :) , I will switch them round to avoid any possible issues.
